# -*- coding: utf-8 -*-
"""multiview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-xBrygIl1JcJeAG0-w4RZE9ipuqh61F
"""

!pip install opencv-contrib-python==4.5.5.64

"""moduleの読み込み"""

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt

color_num = 3
filename = 'gallery_input.avi'

"""動画の読み込み"""

v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

"""動画データの取得"""

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

"""フレームの取り出し"""

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

for j in range(frame_num):
  cv2_imshow(frames[j])



print(frames.shape)

color_num = 3
Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  for j in range(color_num):
    Fdash[i,:,j] = frames[i,:,:,j].flatten()

print(frames.shape)
print(Fdash.shape)

"""最適化を行う関数"""

lamda = 1/max(frame_height,frame_width)
lam1 = 50 * lamda
lam2 = 2000 * lamda
lam3 = 10 * lamda



def optimize(F,thr = 100,max_iter = 30):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  F = np.clip(F, 0,255).astype(np.int32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.001
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)

  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
    print(f"count:{count}")
    #for i in range(color_num):
    #  U1, S1, V1 = LA.svd(B[:,:,i] + Y2* Invmu, full_matrices=False)
    #  U2, S2, V2 = LA.svd(B[:,:,i] + Y2* Invmu, full_matrices=False)
    #  U3, S3, V3 = LA.svd(B[:,:,i] + Y2* Invmu, full_matrices=False)

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.int32)
    S = S.astype(np.int32)
    Vh = Vh.astype(np.int32)
    S_lowrank = S_lowrank.astype(np.int32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      #C[:,:,i] = shrinkage_operator()
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      #T = F - E N + Invmu * Y1 + A -Invmu * Y2 + transpose(D)*(C - Invmu * Y3)
      B[:,:,i] = (1/2)*T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      #Y3[:,:,i] = Y3[:,:,i] + mu * (D * B - C)

    error = LA.norm(B - A) + LA.norm(F - B - E - N)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B

"""SIFTの使い方"""

(frame_num+1)/2

img = frames[int((frame_num+1)/2)]

#sift = cv2.xfeatures2d.SIFT_create()
sift = cv2.SIFT_create()

kp0, des0 = sift.detectAndCompute(img, None)

img_sift = cv2.drawKeypoints(img, kp0, None, flags=4)
cv2_imshow(img_sift)
#cv2.imwrite("sift_img.jpg",img_sift)

(frame_num+1)/2

img = frames[int((frame_num+1)/2)]

surf = cv2.xfeatures2d.SURF_create()

kp0, des0 = surf.detectAndCompute(img, None)

img_surf = cv2.drawKeypoints(img, kp0, None, flags=4)
cv2_imshow(img_surf)
#cv2.imwrite("sift_img.jpg",img_sift)

"""1枚の画像の画像と合わせたい画像のマッチング"""

img = frames[int((frame_num)/2)]


#sift = cv2.xfeatures2d.SIFT_create()


sift = cv2.SIFT_create()

#真ん中の画像imgの特徴量抽出
kp0, des0 = sift.detectAndCompute(img, None)

#各framesの特徴量抽出
kp_list = []
des_list = []

for i in range(frame_num):
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)

#マッチングペアの作成
bf = cv2.BFMatcher()
#matches = bf.knnMatch(des0,des_list[1], k=min(len(kp_list[1]),len(kp0)))
matches = bf.knnMatch(des0,des_list[6], k=2)
#matches = bf.match(des0, des_list[1])

# Lowe's ratio test
good_matches = []
for m, n in matches:
  if m.distance < 0.45 * n.distance:
    good_matches.append(m)
#matches_list.append(good_matches)

sift_matches = cv2.drawMatches(img, kp0, frames[6], kp_list[6], good_matches, None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

#sift_matches = cv2.drawMatchesKnn(img,kp0,frames[1],kp_list[1],matches,None,flags=2)

# 表示
plt.figure(figsize=(12, 6))
plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.title("SIFT Matching")
plt.show()



#KP = np.array(kp_list)
print(len(kp_list))
print(len(kp_list[1]))

"""すべての画像でマッチング"""

img = frames[int((frame_num)/2)]

#sift = cv2.xfeatures2d.SIFT_create()


sift = cv2.SIFT_create()

#真ん中の画像imgの特徴量抽出
kp0, des0 = sift.detectAndCompute(img, None)


#各framesの特徴量抽出
kp_list = []
des_list = []

for i in range(frame_num):
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)


bf_list = []
matches_list = []

for i in range(frame_num):
  #マッチングペアの作成

  bf = cv2.BFMatcher()
  mat = bf.match(des0, des_list[i])
  good_match = []

  #特徴点の座標抽出
  pts1 = np.float32([kp_list[i][m.trainIdx].pt for m in mat]).reshape(-1, 1, 2)
  pts2 = np.float32([kp0[m.queryIdx].pt for m in mat]).reshape(-1, 1, 2)
  for j in range(len(mat)):
    x_pt = np.array([pts1[j,0,0], pts1[j,0,1], 1])
    y_pt = np.array([pts2[j,0,0], pts2[j,0,1], 1])
    x = Tb_list[i] @ x_pt
    y = y_pt
    x = x/x[2]
    y = y/y[2]

    if np.linalg.norm(x-y) > dis:
      good_match.append(mat[j])
  matches_list.append(mat)

  sift_matches = cv2.drawMatches(img, kp0, frames[i], kp_list[i], matches_list[i], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

  #plt.figure(figsize=(12, 6))
  plt.figure(figsize=(20, 10))
  plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
  plt.axis('off')

  plt.title(f"SIFT Matching[{i}]")
  plt.show()

"""すべての画像でHomography変換"""

img = frames[int((frame_num)/2)]

#sift = cv2.xfeatures2d.SIFT_create()


sift = cv2.SIFT_create()

#真ん中の画像imgの特徴量抽出
kp0, des0 = sift.detectAndCompute(img, None)


#各framesの特徴量抽出
kp_list = []
des_list = []

for i in range(frame_num):
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)


bf_list = []
matches_list = []

H_list = []
H_Inv_List = []
for i in range(frame_num):
  #マッチングペアの作成

  bf = cv2.BFMatcher()
  mat = bf.match(des0, des_list[i])
  matches_list.append(mat)

  #ソート
  matches_list[i] = sorted(matches_list[i], key=lambda x: x.distance)

  #特徴点の座標抽出
  ref_pts = np.float32([kp_list[i][m.trainIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)
  o_pts = np.float32([kp0[m.queryIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)

  # Homography行列を推定（frames[i] → img）
  H, mask = cv2.findHomography(ref_pts, o_pts, cv2.RANSAC, 5.0)
  H_list.append(H)
  H_Inv = LA.inv(H)
  H_Inv_List.append(H_Inv)

  # 射影変換でframes[i]をimgに合わせる
  if H is not None:
      h, w = img.shape[:2]
      warped_img = cv2.warpPerspective(frames[i], H_list[i], (w, h))

      # 表示
      plt.figure(figsize=(18, 6))
      plt.imshow(cv2.cvtColor(warped_img, cv2.COLOR_BGR2RGB))
      plt.title(f"Warped frames[{i}] to match img")
      plt.axis('off')
      plt.show()
  else:
      print(f"Homography matrix{i} could not be estimated.")

H_list[int((frame_num)/2)] = np.eye(N = 3)
H_Inv_List[int((frame_num)/2)] = np.eye(N = 3)

"""1枚の画像でHomography変換"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

# 中央のフレームを選ぶ
img = frames[int((frame_num + 1) / 2)]

# SIFTオブジェクト作成
sift = cv2.SIFT_create()
kp0, des0 = sift.detectAndCompute(img, None)

# すべてのフレームに対して特徴量を検出
kp_list = []
des_list = []
for i in range(frame_num):
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)

# 特徴点マッチング
bf = cv2.BFMatcher()
matches = bf.match(des0, des_list[1])

# ソート（距離が短い順）
matches = sorted(matches, key=lambda x: x.distance)

# 特徴点の座標抽出
src_pts = np.float32([kp_list[1][m.trainIdx].pt for m in matches]).reshape(-1, 1, 2)  # frames[1]
dst_pts = np.float32([kp0[m.queryIdx].pt for m in matches]).reshape(-1, 1, 2)        # img

# Homography行列を推定（frames[1] → img）
H, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)

# 射影変換でframes[1]をimgに合わせる
if H is not None:
    h, w = img.shape[:2]
    warped_img = cv2.warpPerspective(frames[1], H, (w, h))

    # 表示
    plt.figure(figsize=(18, 6))

    plt.subplot(1, 3, 1)
    plt.imshow(cv2.cvtColor(frames[1], cv2.COLOR_BGR2RGB))
    plt.title("Original frames[1]")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title("Target img")
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(cv2.cvtColor(warped_img, cv2.COLOR_BGR2RGB))
    plt.title("Warped frames[1] to match img")
    plt.axis('off')

    plt.show()
else:
    print("Homography matrix could not be estimated.")

import cv2
import matplotlib.pyplot as plt
import numpy as np

img = frames[int((frame_num)/2)]

sift = cv2.SIFT_create()

# 真ん中の画像の特徴量
kp0, des0 = sift.detectAndCompute(img, None)

# 各フレームの特徴量
kp_list = []
des_list = []

for i in range(frame_num):
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)

matches_list = []
H_list = []
H_inv_list = []  # ← 逆行列リスト追加

for i in range(frame_num):
    # マッチング
    bf = cv2.BFMatcher()
    mat = bf.match(des0, des_list[i])
    mat = sorted(mat, key=lambda x: x.distance)
    matches_list.append(mat)

    # 特徴点ペア
    ref_pts = np.float32([kp_list[i][m.trainIdx].pt for m in mat]).reshape(-1, 1, 2)
    o_pts = np.float32([kp0[m.queryIdx].pt for m in mat]).reshape(-1, 1, 2)

    # Homography推定（frames[i] → img）
    H, mask = cv2.findHomography(ref_pts, o_pts, cv2.RANSAC, 5.0)
    H_list.append(H)

    if H is not None and H.shape == (3, 3):
      ######################################
        # 逆行列（img → frames[i] に戻す変換）
        H_inv = np.linalg.inv(H)
        H_inv_list.append(H_inv)
        ######################################

        # ワープ（frames[i] → img）
        h, w = img.shape[:2]
        warped_img = cv2.warpPerspective(frames[i], H, (w, h))

        # ワープ戻し（img → frames[i] に戻す）
        recovered_img = cv2.warpPerspective(warped_img, H_inv, (frames[i].shape[1], frames[i].shape[0]))

        # 表示
        plt.figure(figsize=(18, 6))

        plt.subplot(1, 3, 1)
        plt.imshow(cv2.cvtColor(frames[i], cv2.COLOR_BGR2RGB))
        plt.title(f"Original frames[{i}]")
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(cv2.cvtColor(warped_img, cv2.COLOR_BGR2RGB))
        plt.title(f"Warped to match img")
        plt.axis('off')

        plt.subplot(1, 3, 3)
        plt.imshow(cv2.cvtColor(recovered_img, cv2.COLOR_BGR2RGB))
        plt.title(f"Recovered (img → frames[{i}])")
        plt.axis('off')

        plt.show()
    else:
        print(f"Homography matrix {i} could not be estimated or is invalid.")
        H_inv_list.append(None)

for i in range(frame_num):
  print(H_list[i])
  print()

"""img_to_mat関数は切り出した画像framesを行列の形Fに変換

mat_to_img関数は行列Fを画像の形framesに変換

"""

def img_to_mat(frames):
  Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      Fdash[i,:,j] = frames[i,:,:,j].flatten()

  return Fdash

print(frames.shape)
A = img_to_mat(frames)
print(A.shape)
print()

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

print(Fdash.shape)
imgs = mat_to_img(A)
print(imgs.shape)

import numpy as np
X = np.array([[1, 2], [3, 4], [5, 6]])
print(X)
print(X.shape)
Y = X.flatten()
X = Y.reshape(3,2)
print(Y)
print(X)

"""変換行列を作成する関数

画像frames、合わせる対象画像imgを入力引数

変換行列H_list、逆変換行列H_Inv_listを戻り値とする
"""

def Make_T(frames,img):
  sift = cv2.SIFT_create()

  #imgの特徴量抽出
  kp0, des0 = sift.detectAndCompute(img, None)


  kp_list = []
  des_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):

    #各framesの特徴量抽出
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)

    #マッチングペアの作成
    bf = cv2.BFMatcher()
    mat = bf.match(des0, des_list[i])
    matches_list.append(mat)

    #ソート
    matches_list[i] = sorted(matches_list[i], key=lambda x: x.distance)

    #特徴点の座標抽出
    ref_pts = np.float32([kp_list[i][m.trainIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)
    o_pts = np.float32([kp0[m.queryIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)

    # Homography行列を推定（frames[i] → img）
    H, mask = cv2.findHomography(ref_pts, o_pts, cv2.RANSAC, 5.0)
    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)

  return H_list, H_Inv_List

"""行列Fdashに対して変換行列H_listで変換した行列を得る関数"""

def TP(Fdash,H_list):
  frames = mat_to_img(Fdash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

"""行列Fに対して中央の画像に合わせる変換行列を生成する関数"""

def Get_T(R_dash):
  Rdash_frames = mat_to_img(Rdash)
  T, T_Inv = Make_T(Rdash_frames,Rdash_frames[int((frame_num)/2)])

  return T,T_Inv

from ast import FormattedValue
def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

def arrange_mat(F):
  for i in range(frame_num):
    for j in range(color_num):
      for k in range(int(frame_height) * int(frame_width)):
        F[i,k,j] = min(int(F[i,k,j]), 255)
        F[i,k,j] = max(int(F[i,k,j]), 0)
  return F

def mat_cal_uint8(A,B,m):
  if A.shape == B.shape:

    C = np.zeros_like(A)
  else:
    print("error:diff-size")

  if m == 0:
    for i in range(frame_num):
      for j in range(color_num):
        for k in range(int(frame_height) * int(frame_width)):
          C[i,k,j] = min(A[i,k,j] + B[i,k,j],255)
  elif (m == 1):
    for i in range(frame_num):
      for j in range(color_num):
        for k in range(int(frame_height) * int(frame_width)):
          C[i,k,j] = max(A[i,k,j] - B[i,k,j],0)
  else:
    print("error:m is 0 or 1")

  return C

def cal_uint8(A,B,m):
  A_uint16 = A.astype(np.uint16)
  B_uint16 = B.astype(np.uint16)
  if m == 0:
    C_uint16 = A_uint16 + B_uint16
  elif (m == 1):
    C_uint16 = A_uint16 - B_uint16
  else:
    print("error:m is 0 or 1")

  C = np.clip(C_uint16.astype(np.uint8),0,255)
  return C

mid = int((frame_num)/2)
max_iter = 1
thr = 10


#Initialize


B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)
Tb, Tb_Inv = Make_T(frames,frames[mid])
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

Bdash = TP(B,Tb_Inv)

#Rdash
Rdash = Fdash - Bdash

Rdash_frames = mat_to_img(Rdash)
Tr, Tr_Inv = Make_T(Rdash_frames,Rdash_frames[mid])
Fr = TP(Rdash,Tr)

rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  F = TP(Fdash,Tb) - TP(TP(R,Tr_Inv),Tb)
  B = optimize(F,thr)

  #get new tr
  Rdash = Fdash - TP(B,Tb_Inv)
  Tr, Tr_Inv = Get_T(Rdash)

  #optimizeR
  F = TP(Fdash,Tr) - TP(TP(B,Tb_Inv),Tr)
  R = optimize(F,thr)

  #get new tb
  Bdash = Fdash - TP(R,Tr_Inv)
  Tb, Tb_Inv = Get_T(Bdash)

  count = count + 1

print(F)

Bimage = mat_to_img(B)
Rimage = mat_to_img(R)

print(Bimage.shape)
for i in range(frame_num):
  cv2_imshow(Bimage[i])
  cv2_imshow(Rimage[i])
  print(i)

print(B)

"""エッジ処理"""

def Make_edge_3D(D,B):
  DB = np.zeros_like(B).astype(int)

  for i in range(color_num):
    DB[:,:,i] = B[:,:,i] @ D[:,:,i].T
  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

def Make_edge_D1(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+1)%size,k])
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+int(frame_width))%size,k])
        DB[i,j,k] = 2 * int(B[i,j%size,k]) - int(B[i,(j+1)%size,k]) - int(B[i,(j+int(frame_width))%size,k])

  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

def Make_edge_2d(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      DB[i,j] = 2 * int(B[i,j%size]) - int(B[i,(j+1)%size]) - int(B[i,(j+int(frame_width))%size])

  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

def Make_edge_D2(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  w = int(frame_width)

  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        DB[i,j,k] = int(B[i,(j+1)%size,k]) - int(B[i,(j-1)%size,k]) + int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) - int(B[i,(j-1+w)%size,k])
        DB[i,j,k] += int(B[i,(j+w)%size,k]) - int(B[i,(j-w)%size,k]) - int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) + int(B[i,(j-1+w)%size,k])

  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

def Make_DC(C):
  DC = np.zeros_like(C).astype(int)
  size = C.shape[1]
  w = int(frame_width)

  for i in range(C.shape[0]):
    for j in range(C.shape[1]):
      DC[i,j] = 2 * int(C[i,j%size]) - int(C[i,(j-1)%size]) - int(C[i,(j-w)%size])

  DC = np.clip(np.abs(DC),0,255).astype(np.uint8)
  return DC




def Wb_update(Gf,Gr):
  Gb = np.zeros_like(Gf).astype(float)
  Hr = np.zeros_like(Gr).astype(float)
  Hb = np.zeros_like(Gr).astype(float)
  Hf = np.zeros_like(Gf).astype(float)
  Wb = np.zeros_like(Gf).astype(float)
  m = 3
  # ratio = a
  thr = 0.05 * 255
  a = 1.2

  Gb = np.clip(Gf - Gr,0,255)
  Hf = np.where(Gf >thr, 255, 0)
  Hb = np.where(Gb > thr, 255, 0)
  Hr = np.where(Gr > thr, 255, 0)

  Wb = Wb + 1

  for i in range(int(frame_height) * int(frame_width)):

    for j in range(frame_num):
      for k in range(color_num):
        if(Hf[j,i,k] == 1 and Gb[j,i,k] > a * Gr[j,i,k]):
          Wb[j,i,k] = 0

        elif(Hf[j,i,k] == 1 and Gr[j,i,k] > a * Gb[j,i,k]):
          Wb[j,i,k] = 5

        elif(Gb[j,i,k] > thr or Gr[j,i,k] > thr):
          Wb[j,i,k] = 5

        else:
          Wb[j,i,k] = 1
    for k in range(color_num):
      if(sum(Wb[:,i,k]) < 3):
        Wb[:,i,k] = 0

  Wb = np.clip(Wb,0,255).astype(np.uint8)
  return Wb

def MakeD(size):
  D = np.zeros((size, size, 3), dtype=np.int8)

  for i in range(size):
    for k in range(color_num):
      D[(i)%size, (i-1)%size,k] = 1
      D[(i)%size, i%size,k] = -1

  return D

def

#print(F.shape)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue

color_num = 3
filename = 'gallery_input.avi'




v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)




def optimize(F,Wb,thr = 10,max_iter = 300):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  def C_opt(Cin,Wb,Invmu):
    C = np.zeros_like(Cin)

    return shrinkage_operator(Cin, Wb * lam3 * Invmu)
    '''
    for i in range(frame_num):
      for j in range(Cin.shape[1]):
        C[i,j] = shrinkage_operator(Cin[i,j],Wb[i,j]*lam3*Invmu)

    return C
    '''


  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.05
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)



  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"opt_count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      C[:,:,i] = C_opt(Make_edge_2d(B[:,:,i]) + Invmu * Y3[:,:,i],Wb[:,:,i],Invmu)
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      #T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i] + Make_DC(C[:,:,i] - Invmu * Y3[:,:,i])
      B[:,:,i] = (1/6)*T
      #B[:,:,i] = Inv(transpose(D[:,:,i]) @ D[:,:,i] + 2*I ) * T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      Y3[:,:,i] = Y3[:,:,i] + mu * (Make_edge_2d(B[:,:,i]) - C[:,:,i])

    error = LA.norm(B - A) + LA.norm(F - B - E - N) + LA.norm(Make_edge_D1(B) - C)
    #error = LA.norm(B - A) + LA.norm(F - B - E - N) + LA.norm(D @ B - C)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      Fdash[i,:,j] = frames[i,:,:,j].flatten()

  return Fdash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def Make_T(frames,img,Tb_list):
  sift = cv2.SIFT_create()

  #imgの特徴量抽出
  kp0, des0 = sift.detectAndCompute(img, None)


  kp_list = []
  des_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):

    #各framesの特徴量抽出
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)

    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      #dis = max(frame_height,frame_width)/500.0
      dis = 5.0
      bf = cv2.BFMatcher()

      mat = bf.match(des0, des_list[i])

      matknn = bf.knnMatch(des0, des_list[i], k=2)

      # Lowe's ratio test
      mat = []
      for m, n in matknn:
          if m.distance < 0.65 * n.distance:
              mat.append(m)



      good_match = []

      #特徴点の座標抽出
      pts1 = np.float32([kp_list[i][m.trainIdx].pt for m in mat]).reshape(-1, 1, 2)
      pts2 = np.float32([kp0[m.queryIdx].pt for m in mat]).reshape(-1, 1, 2)

      for j in range(len(mat)):
        x_pt = np.array([pts1[j,0,0], pts1[j,0,1], 1.0])
        y_pt = np.array([pts2[j,0,0], pts2[j,0,1], 1.0])
        x = Tb_list[i] @ x_pt
        y = Tb_list[i] @ y_pt
        x = x/x[2]
        y = y/y[2]

        if np.linalg.norm(x - y) > dis:
          good_match.append(mat[j])

      matches_list.append(good_match)
      #matches_list.append(mat)

    elif mode == 0:
      bf = cv2.BFMatcher()
      '''
      mat = bf.match(des0, des_list[i])
      matches_list.append(mat)
      '''

      mat = bf.knnMatch(des0, des_list[i], k=2)

      # Lowe's ratio test
      good_matches = []
      for m, n in mat:
          if m.distance < 0.65 * n.distance:
              good_matches.append(m)
      matches_list.append(good_matches)


    #ソート
    matches_list[i] = sorted(matches_list[i], key=lambda x: x.distance)


    #特徴点の座標抽出
    ref_pts = np.float32([kp_list[i][m.trainIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)
    o_pts = np.float32([kp0[m.queryIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)
    '''
    sift_matches = cv2.drawMatches(img, kp0, frames[i], kp_list[i], matches_list[i], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title("SIFT Matching")
    plt.show()
    '''
    # Homography行列を推定（frames[i] → img）
    if len(ref_pts) > 4 and len(o_pts) > 4:
      H, mask = cv2.findHomography(ref_pts, o_pts, cv2.RANSAC, 4.0)
    else:
      H = np.eye(3)
    if H is None:
      H = np.eye(3)
    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)

  '''
  sift_matches = cv2.drawMatches(img, kp0, frames[4], kp_list[4], matches_list[4], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
  # 表示
  plt.figure(figsize=(12, 6))
  plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
  plt.axis('off')
  plt.title("SIFT Matching")
  plt.show()
  '''

  return H_list, H_Inv_List

def TP(Fdash,H_list):
  frames = mat_to_img(Fdash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

def Get_T(R_dash,Tb_list):
  Rdash_frames = mat_to_img(Rdash)
  T, T_Inv = Make_T(Rdash_frames,Rdash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

#main

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 2000 * lamda
lam3 = 10 * lamda
thr = 10

mid = int((frame_num)/2)
max_iter = 1
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize
D = MakeD(Fdash.shape[1])

B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(Rdash,Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)



#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))

  #Wb_update
  Wb = Wb_update(Make_edge_D1(TP(Fdash,Tb)),Make_edge_D1(TP(TP(R,Tr_Inv),Tb)))

  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,Wb,thr)
  print("check_B")
  check_img(B)

  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  Tr, Tr_Inv = Get_T(Rdash,Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #Wr_update
  Wr = Wb_update(Make_edge_D1(TP(Fdash,Tr)),Make_edge_D1(TP(TP(B,Tb_Inv),Tr)))

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,Wr,thr)
  print("check_R")
  check_img(R)

  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(Bdash,Tr)

  count = count + 1

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue


frame_num = 5
filename = "toy"
im = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_input_{i+1}.png')
  temp = cv2.imread(img_file)
  im.append(temp)
  cv2_imshow(im[i])
  print(im[i].shape)
  print(im[i].dtype)


frame_height = im[0].shape[0]
frame_width = im[0].shape[1]
mid = int((frame_num)/2)

#print(F.shape)

color_num = 3
MAX_PIXEL = 255
MIN_PIXEL = 0

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 1000 * lamda
lam3 = 10 * lamda
thr = 10

tr_bg = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_bg_{i+1}.png')
  temp = cv2.imread(img_file)
  tr_bg.append(temp)
  #cv2_imshow(truth_bg[i])
  print(tr_bg[i].shape)
  print(tr_bg[i].dtype)


tr_rf = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_rf_{i+1}.png')
  temp = cv2.imread(img_file)
  tr_rf.append(temp)
  #cv2_imshow(truth_rf[i])
  print(tr_rf[i].shape)
  print(tr_rf[i].dtype)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)
truth_bg = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)
truth_rf = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  frames[i] = im[i]
  truth_bg[i] = tr_bg[i]
  truth_rf[i] = tr_rf[i]

  # True

  print(type(frames))
  # <class 'numpy.ndarray'>

  print(frames.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

mid = int((frame_num)/2)

def img_to_mat(frames):
  F_dash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      F_dash[i,:,j] = frames[i,:,:,j].flatten()

  return F_dash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

def Make_edge_D1(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+1)%size,k])
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+int(frame_width))%size,k])
        DB[i,j,k] = 2 * int(B[i,j%size,k]) - int(B[i,(j+1)%size,k]) - int(B[i,(j+int(frame_width))%size,k])

  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

def Make_edge_D2(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  w = int(frame_width)

  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        DB[i,j,k] = int(B[i,(j+1)%size,k]) - int(B[i,(j-1)%size,k]) + int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) - int(B[i,(j-1+w)%size,k])
        DB[i,j,k] += int(B[i,(j+w)%size,k]) - int(B[i,(j-w)%size,k]) - int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) + int(B[i,(j-1+w)%size,k])

  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

def color_to_gray(F_color):
  F_gray = np.zeros((frame_num, frame_height * frame_width), dtype=np.uint8)
  for i in range(frame_num):
    r = F_color[i,:,2].astype(float)
    g = F_color[i,:,1].astype(float)
    b = F_color[i,:,0].astype(float)
    gray = 0.299 * r + 0.587 * g + 0.114 * b
    F_gray[i,:] = np.clip(gray, 0, 255).astype(np.uint8)
  return F_gray

def check_gray_img(F_gray):
  for i in range(frame_num):
    gray_img = F_gray[i].reshape(frame_height, frame_width)
    cv2_imshow(gray_img)
    print(i)


#DF = Make_edge_D2(img_to_mat(frames))
#check_img(DF)

DF = Make_edge_D1(img_to_mat(frames))
DF_gray = color_to_gray(DF)
#check_gray_img(np.clip(15*DF_gray.astype(np.int32),0,255).astype(np.uint8))
check_gray_img(DF_gray)

print(D[0:9,0:9,0])
print(-1%Fdash.shape[1])

#print(F.shape)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue

color_num = 3
filename = 'night3_input.avi'




v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)




def optimize(F,thr = 10,max_iter = 300):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  def C_opt(Cin,Wb,Invmu):
    C = np.zeros_like(Cin)

    for i in range(frame_num):
      for j in range(Cin.shape[1]):
        C = shrinkage_operator(Cin[i,j],Wb[i,j]*lam3*Invmu)

    return C


  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.05
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)



  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"opt_count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      #C[:,:,i] = C_opt(D[:,:,i] @ B[:,:,i] + Invmu * Y3[:,:,i],Wb,Invmu)
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      #T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i] + transpose(D[:,:,i]) @ (C[:,:,i] - Invmu * Y3[:,:,i])
      B[:,:,i] = (1/2)*T
      #B[:,:,i] = Inv(transpose(D[:,:,i]) @ D[:,:,i] + 2*I ) * T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      #Y3[:,:,i] = Y3[:,:,i] + mu * (D[:,:,i] @ B[:,:,i] - C[:,:,i])

    error = LA.norm(B - A) + LA.norm(F - B - E - N)
    #error = LA.norm(B - A) + LA.norm(F - B - E - N) + LA.norm(D @ B - C)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      Fdash[i,:,j] = frames[i,:,:,j].flatten()

  return Fdash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def Make_T(frames,img,Tb_list):
  sift = cv2.SIFT_create()

  #imgの特徴量抽出
  kp0, des0 = sift.detectAndCompute(img, None)


  kp_list = []
  des_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):

    #各framesの特徴量抽出
    kp, des = sift.detectAndCompute(frames[i], None)
    kp_list.append(kp)
    des_list.append(des)

    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      #dis = max(frame_height,frame_width)/500.0
      dis = 5.0
      bf = cv2.BFMatcher()

      mat = bf.match(des0, des_list[i])

      matknn = bf.knnMatch(des0, des_list[i], k=2)

      # Lowe's ratio test
      mat = []
      for m, n in matknn:
          if m.distance < 0.65 * n.distance:
              mat.append(m)



      good_match = []

      #特徴点の座標抽出
      pts1 = np.float32([kp_list[i][m.trainIdx].pt for m in mat]).reshape(-1, 1, 2)
      pts2 = np.float32([kp0[m.queryIdx].pt for m in mat]).reshape(-1, 1, 2)

      for j in range(len(mat)):
        x_pt = np.array([pts1[j,0,0], pts1[j,0,1], 1.0])
        y_pt = np.array([pts2[j,0,0], pts2[j,0,1], 1.0])
        x = Tb_list[i] @ x_pt
        y = Tb_list[i] @ y_pt
        x = x/x[2]
        y = y/y[2]

        if np.linalg.norm(x - y) > dis:
          good_match.append(mat[j])

      matches_list.append(good_match)
      #matches_list.append(mat)

    elif mode == 0:
      bf = cv2.BFMatcher()
      '''
      mat = bf.match(des0, des_list[i])
      matches_list.append(mat)
      '''

      mat = bf.knnMatch(des0, des_list[i], k=2)

      # Lowe's ratio test
      good_matches = []
      for m, n in mat:
          if m.distance < 0.65 * n.distance:
              good_matches.append(m)
      matches_list.append(good_matches)


    #ソート
    matches_list[i] = sorted(matches_list[i], key=lambda x: x.distance)


    #特徴点の座標抽出
    ref_pts = np.float32([kp_list[i][m.trainIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)
    o_pts = np.float32([kp0[m.queryIdx].pt for m in matches_list[i]]).reshape(-1, 1, 2)
    '''
    sift_matches = cv2.drawMatches(img, kp0, frames[i], kp_list[i], matches_list[i], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title("SIFT Matching")
    plt.show()
    '''
    # Homography行列を推定（frames[i] → img）
    if len(ref_pts) > 4 and len(o_pts) > 4:
      H, mask = cv2.findHomography(ref_pts, o_pts, cv2.RANSAC, 4.0)
    else:
      H = np.eye(3)
    if H is None:
      H = np.eye(3)
    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)

  '''
  sift_matches = cv2.drawMatches(img, kp0, frames[4], kp_list[4], matches_list[4], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
  # 表示
  plt.figure(figsize=(12, 6))
  plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
  plt.axis('off')
  plt.title("SIFT Matching")
  plt.show()
  '''

  return H_list, H_Inv_List

def TP(Fdash,H_list):
  frames = mat_to_img(Fdash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

def Get_T(R_dash,Tb_list):
  Rdash_frames = mat_to_img(Rdash)
  T, T_Inv = Make_T(Rdash_frames,Rdash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

#main

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 1000 * lamda
lam3 = 10 * lamda
thr = 10

mid = int((frame_num)/2)
max_iter = 3
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize
D = np.zeros((Fdash.shape[1], Fdash.shape[1], 3), dtype=np.int8)


for i in range(Fdash.shape[1]):
  for k in range(color_num):
    D[(i)%Fdash.shape[1], (i-1)%Fdash.shape[1],k] = 1
    D[(i)%Fdash.shape[1], i%Fdash.shape[1],k] = -1

B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(Rdash,Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)


'''
#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))

  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,thr)
  print("check_B")
  check_img(B)

  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  Tr, Tr_Inv = Get_T(Rdash,Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,thr)
  print("check_R")
  check_img(R)

  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(Bdash,Tr)

  count = count + 1

'''

print(Bdash[0,50000:50010,0])
print(Bdash[0,50000:50010,1])
print(Bdash[0,50000:50010,2])

print()
print(Fdash[0,50000:50010,0])
print(Fdash[0,50000:50010,1])
print(Fdash[0,50000:50010,2])

print()
print(Rdash[0,50000:50010,0])
print(Rdash[0,50000:50010,1])
print(Rdash[0,50000:50010,2])

print()
print(B[0,50000:50010,0])
print(B[0,50000:50010,1])
print(B[0,50000:50010,2])

#pip install opencv-contrib-python

max(frame_height,frame_width)/250.0

img = frames[int((frame_num+1)/2)]

surf = cv2.xfeatures2d.SURF_create()

kp0, des0 = surf.detectAndCompute(img, None)

img_surf = cv2.drawKeypoints(img, kp0, None, flags=4)
cv2_imshow(img_surf)

def rpca(M, max_iter=800,p_interval=50):
    def shrinkage_operator(x, tau):
        return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

    def svd_thresholding_operator(X, tau):
        U, S, Vh = LA.svd(X, full_matrices=False)
        return U @ np.diag(shrinkage_operator(S, tau)) @ Vh

    i = 0
    S = np.zeros_like(M)
    Y = np.zeros_like(M)
    error = np.Inf
    tol = 1e-7 * LA.norm(M, ord="fro")
    mu = M.shape[0] * M.shape[1]/(4 * LA.norm(M, ord=1))
    mu_inv = 1/mu
    lam = 1/np.sqrt(np.max(M.shape))

    while i < max_iter:
        L = svd_thresholding_operator(M - S + mu_inv * Y, mu_inv)
        S = shrinkage_operator(M - L + mu_inv * Y, lam * mu_inv)
        Y = Y + mu * (M - L - S)
        error = LA.norm(M - L - S, ord='fro')
        if i % p_interval == 0:
            print("step:{} error:{}".format(i, error))

        if error <= tol:
            print("converted! error:{}".format(error))
            break
        i+=1
    else:
        print("Not converged")

    return L, S

def prepare_frames_to_use(video_path="filename",#画像のパス
                          start_frame=0,#最初のフレーム
                          end_frame=5,#最後のフレーム
                          r=1,#画像縮小パラメータ
                          ):

    #画像読み込み
    cap = cv2.VideoCapture(video_path)

    #画像の解像度、フレームレート、フレーム数取得
    wid = cap.get(cv2.CAP_PROP_FRAME_WIDTH)#横
    wid_r = int(wid/r)
    hei = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)#縦
    hei_r = int(hei/r)
    fps = cap.get(cv2.CAP_PROP_FPS)#フレームレート
    count = cap.get(cv2.CAP_PROP_FRAME_COUNT)#フレーム数
    dt = 1/fps#フレーム間秒数
    print(f"wid:{wid}", f" hei:{hei}", f" fps:{fps}", f" count:{count}", f"dt:{dt}")

    #対象フレーム抜き出し
    cat_frames = []
    cap.set(cv2.CAP_PROP_POS_FRAMES,start_frame)
    for i in range(end_frame - start_frame):
        ret, img = cap.read()
        if not ret:
            print("no image")
            break
        buf = cv2.cvtColor(cv2.resize(img,(wid_r, hei_r)),
                           cv2.COLOR_BGR2GRAY).flatten()#
        cat_frames.append(buf)
        print(i)
        print(buf.shape)

    cap.release()
    cat_frames = np.array(cat_frames).T
    return cat_frames, wid_r, hei_r, fps

#prepare_frames_to_use

#frames, wid, hei, fps = prepare_frames_to_use()
#print(frame[:,:,1].shape)
print(frames.shape)