# -*- coding: utf-8 -*-
"""multiview3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PlY7DIY7ZhtTVPhnFmzvLYRzRmQPQLpx
"""

from google.colab import drive
drive.mount('/content/drive')

!apt-get update
!apt-get install -y build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev

!git clone https://github.com/opencv/opencv.git
!git clone https://github.com/opencv/opencv_contrib.git

# Commented out IPython magic to ensure Python compatibility.
import os
os.makedirs("opencv_build", exist_ok=True)
# %cd opencv_build

!cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
    -D ENABLE_PRECOMPILED_HEADERS=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D BUILD_EXAMPLES=OFF \
    ../opencv

!make -j4
!make install
!ldconfig

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue
from matplotlib import pyplot as plt


frame_num = 5
filename = "toy"
im = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_input_{i+1}.png')
  temp = cv2.imread(img_file)
  im.append(temp)
  cv2_imshow(im[i])
  print(im[i].shape)
  print(im[i].dtype)


frame_height = im[0].shape[0]
frame_width = im[0].shape[1]
mid = int((frame_num)/2)

#print(F.shape)

color_num = 3
MAX_PIXEL = 255
MIN_PIXEL = 0

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 1000 * lamda
lam3 = 10 * lamda
thr = 10

tr_bg = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_bg_{i+1}.png')
  temp = cv2.imread(img_file)
  tr_bg.append(temp)
  #cv2_imshow(truth_bg[i])
  print(tr_bg[i].shape)
  print(tr_bg[i].dtype)


tr_rf = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_rf_{i+1}.png')
  temp = cv2.imread(img_file)
  tr_rf.append(temp)
  #cv2_imshow(truth_rf[i])
  print(tr_rf[i].shape)
  print(tr_rf[i].dtype)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)
truth_bg = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)
truth_rf = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  frames[i] = im[i]
  truth_bg[i] = tr_bg[i]
  truth_rf[i] = tr_rf[i]

  # True

  print(type(frames))
  # <class 'numpy.ndarray'>

  print(frames.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

mid = int((frame_num)/2)

def optimize(F,thr = 10,max_iter = 300,lam1=lam1, lam2=lam2,lam3=lam3):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.05
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.15
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)

  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      #C[:,:,i] = shrinkage_operator()
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      #T = F - E N + Invmu * Y1 + A -Invmu * Y2 + transpose(D) @ (C - Invmu * Y3)
      B[:,:,i] = (1/2)*T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      #Y3[:,:,i] = Y3[:,:,i] + mu * (D * B - C)

    error = LA.norm(B - A) + LA.norm(F - B - E - N)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  F_dash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      F_dash[i,:,j] = frames[i,:,:,j].flatten()

  return F_dash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def Make_T(frames,img,Tb_list,mid=mid):
  #rans = 4.0
  rans = max(frame_height, frame_width) * 0.01  # 例: 1%の誤差許容


  sift = cv2.SIFT_create()
  surf = cv2.xfeatures2d.SURF_create()

  #imgの特徴量抽出
  kp0_sift, des0_sift = sift.detectAndCompute(img, None)
  kp0_surf, des0_surf = surf.detectAndCompute(img, None)


  kp_sift_list = []
  des_sift_list = []

  kp_surf_list = []
  des_surf_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):


    #各framesの特徴量抽出
    kp_sift, des_sift = sift.detectAndCompute(frames[i], None)
    kp_surf, des_surf = surf.detectAndCompute(frames[i], None)

    #kp = np.concatenate((kp,kp_surf))
    #des = np.concatenate((des,des_surf))

    kp_sift_list.append(kp_sift)
    des_sift_list.append(des_sift)
    kp_surf_list.append(kp_surf)
    des_surf_list.append(des_surf)


    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      dis = max(frame_height,frame_width)/75.0
      #dis = 5.0
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      #mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      #mat_surf = bf_surf.match(des0_surf, des_surf_list[i])


      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test
      mat_sift = []
      mat_surf = []
      for m, n in matknn_sift:
        if m.distance < 0.75 * n.distance:
            mat_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.75 * n.distance:
            mat_surf.append(m)

      good_match_sift = []
      good_match_surf = []

      #特徴点の座標抽出
      pts = []
      pts0 = []

      for m in mat_sift:
        x = kp_sift[m.trainIdx].pt
        y = kp0_sift[m.queryIdx].pt

        #pts.append(kp_sift[m.trainIdx].pt)
        #pts0.append(kp0_sift[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_sift.append(m)

      for m in mat_surf:
        x = kp_surf[m.trainIdx].pt
        y = kp0_surf[m.queryIdx].pt

        #pts.append(kp_surf[m.trainIdx].pt)
        #pts0.append(kp0_surf[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_surf.append(m)

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        print("match_fault")
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

    elif mode == 0:
      mat = []
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      '''
      mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      mat_surf = bf_surf.match(des0_surf, des_surf_list[i])
      '''

      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test

      good_match_sift = []
      good_match_surf = []

      for m, n in matknn_sift:
        if m.distance < 0.90 * n.distance:
            good_match_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.90 * n.distance:
            good_match_surf.append(m)

      pts = []
      pts0 = []

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        print("match_fault")
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])


    #ソート
    matches_list[i][0] = sorted(matches_list[i][0], key=lambda x: x.distance)
    matches_list[i][1] = sorted(matches_list[i][1], key=lambda x: x.distance)

    #kp,desのリスト化
    kp_list = [kp_sift_list,kp_surf_list]
    des_list = [des_sift_list,des_surf_list]

    #特徴点の座標抽出
    ref_pts_sift = np.float32([kp_sift_list[i][m.trainIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)
    o_pts_sift = np.float32([kp0_sift[m.queryIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)

    sift_matches = cv2.drawMatches(img, kp0_sift, frames[i], kp_sift_list[i], matches_list[i][0], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SIFT Matching{i}")
    plt.show()

    #特徴点の座標抽出
    ref_pts_surf = np.float32([kp_surf_list[i][m.trainIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)
    o_pts_surf = np.float32([kp0_surf[m.queryIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)

    surf_matches = cv2.drawMatches(img, kp0_surf, frames[i], kp_surf_list[i], matches_list[i][1], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(surf_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SURF Matching{i}")
    plt.show()


    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)


  return H_list, H_Inv_List

def Make_T_with_TPS(frames, img, Tb_list, mid=0, max_ransac_iter=5):

  import numpy.linalg as LA
  from scipy.spatial.distance import cdist
  from scipy.linalg import solve

  def tps_kernel(r):
    r[r == 0] = 1e-20
    return r**2 * np.log(r)

  def compute_tps_weights(src_pts, dst_pts, reg=1e-3):
    n = src_pts.shape[0]
    K = tps_kernel(cdist(src_pts, src_pts))
    P = np.hstack((np.ones((n, 1)), src_pts))
    L = np.vstack([
        np.hstack([K + reg * np.eye(n), P]),
        np.hstack([P.T, np.zeros((3, 3))])
    ])
    V = np.vstack([dst_pts, np.zeros((3, 2))])
    W = solve(L, V)
    return W[:n], W[n:]

  def compute_tps_transform(src_pts, dst_pts):
    return compute_tps_weights(src_pts, dst_pts)

  H_list = []
  TPS_list = []

  sift = cv2.SIFT_create()
  bf = cv2.BFMatcher()

  kp0, des0 = sift.detectAndCompute(img, None)

  for i in range(len(frames)):
    kp, des = sift.detectAndCompute(frames[i], None)
    matches = bf.knnMatch(des0, des, k=2)

    good_matches = []
    for m, n in matches:
        if m.distance < 0.75 * n.distance:
            good_matches.append(m)

    pts0 = np.float32([kp0[m.queryIdx].pt for m in good_matches])
    pts1 = np.float32([kp[m.trainIdx].pt for m in good_matches])

    # --- マルチホモグラフィRANSAC ---
    used = np.zeros(len(pts0), dtype=bool)
    clusters_src = []
    clusters_dst = []

    for _ in range(max_ransac_iter):
        if np.sum(~used) < 4:
            break
        sel_src = pts1[~used]
        sel_dst = pts0[~used]
        H, mask = cv2.findHomography(sel_src, sel_dst, cv2.RANSAC, 4.0)
        if H is None or np.sum(mask) < 4:
            break
        inliers = np.where(~used)[0][mask.ravel() == 1]
        used[inliers] = True
        clusters_src.append(pts1[inliers])
        clusters_dst.append(pts0[inliers])

    # --- TPS変換を計算 ---
    all_src = np.vstack(clusters_src)
    all_dst = np.vstack(clusters_dst)
    if len(all_src) >= 6:
        w_tps, a_tps = compute_tps_transform(all_src, all_dst)
        TPS_list.append((w_tps, a_tps, all_src))  # TPS変換関数の格納
        H_list.append(None)  # TPSを使うのでHomographyは不要
    else:
        # fallback: homography
        H, _ = cv2.findHomography(pts1, pts0, cv2.RANSAC, 4.0)
        H_list.append(H)
        TPS_list.append(None)

  return H_list, TPS_list

def apply_tps_to_image(img, w_tps, a_tps, control_pts, dsize):
  h, w = dsize
  grid_x, grid_y = np.meshgrid(np.arange(w), np.arange(h))
  grid = np.stack([grid_x.ravel(), grid_y.ravel()], axis=1)

  def tps_kernel(r): return r**2 * np.log(r + 1e-20)
  U = tps_kernel(cdist(grid, control_pts))
  phi = (U @ w_tps) + a_tps[0] + a_tps[1] * grid[:, 0:1] + a_tps[2] * grid[:, 1:2]
  map_x = phi[:, 0].reshape(h, w).astype(np.float32)
  map_y = phi[:, 1].reshape(h, w).astype(np.float32)
  return cv2.remap(img, map_x, map_y, interpolation=cv2.INTER_LINEAR)


def TP(F_dash,H_list):
  frames = mat_to_img(F_dash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  return img_to_mat(warped_img)

def Get_T(R_dash,Tb_list):
  R_dash_frames = mat_to_img(R_dash)
  T, T_Inv = Make_T(R_dash_frames,R_dash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

def NCC(truth, est):
    ncc_ave = []
    for i in range(frame_num):
      #temp= cv2.matchTemplate(est[i], truth[i], cv2.TM_CCOEFF_NORMED)
      #ncc_ave.append(temp)
        for j in range(color_num):
            img1 = truth[i][:,:,j].flatten().astype(np.float32)
            img2 = est[i][:,:,j].flatten().astype(np.float32)

            img1 -= np.mean(img1)
            img2 -= np.mean(img2)

            denom = LA.norm(img1) * LA.norm(img2)
            if denom != 0:
                ncc_ave.append(np.sum(img1 * img2) / denom)
            else:
                ncc_ave.append(0.0)

    return np.mean(ncc_ave)

#main




max_iter = 100
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize


B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(np.clip(2.0*Rdash.astype(np.float32),0,255).astype(np.uint8),Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)


result = []

ncc_bg = NCC(truth_bg, mat_to_img(TP(B,Tb_Inv)))
ncc_rf = NCC(truth_rf, mat_to_img(TP(R,Tr_Inv)))


result.append([ncc_bg, ncc_rf])
print(f"NCC_bg:{ncc_bg}")
print(f"NCC_rf:{ncc_rf}")
#CLORD
count = 0
while (count < max_iter):
  print(f"CLORD_count:{count}")
  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))

  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,thr)
  print("check_B")
  check_img(B)

  img_B = mat_to_img(B)
  for i in range(frame_num):
    cv2.imwrite(f'/content/drive/My Drive/output_bg_{filename}_{i+1}.png', img_B[i])



  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tr, Tr_Inv = Get_T(Rdash,Tb)
  Tr, Tr_Inv = Get_T(np.clip(2.0*Rdash.astype(np.float32),0,255).astype(np.uint8),Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,thr)
  print("check_R")
  check_img(R)

  img_R = mat_to_img(R)
  for i in range(frame_num):
    cv2.imwrite(f'/content/drive/My Drive/output_rf_{filename}_{i+1}.png', img_R[i])


  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(np.clip(2.0*Bdash.astype(np.float32),0,255).astype(np.uint8),Tr)


  #result.append([NCC(mat_to_img(TP(img_to_mat(truth_bg),Tb)),mat_to_img(B)),NCC(mat_to_img(TP(img_to_mat(truth_rf),Tr)),mat_to_img(R))])
  #print(f"NCC_bg:{result[count][0]}")
  #print(f"NCC_rf:{result[count][1]}")

  #ncc_bg = NCC(mat_to_img(TP(img_to_mat(truth_bg), Tb)), mat_to_img(B))
  #ncc_rf = NCC(mat_to_img(TP(img_to_mat(truth_rf), Tr)), mat_to_img(R))

  ncc_bg = NCC(truth_bg, mat_to_img(TP(B,Tb_Inv)))
  ncc_rf = NCC(truth_rf, mat_to_img(TP(R,Tr_Inv)))


  result.append([ncc_bg, ncc_rf])
  print(f"NCC_bg:{ncc_bg}")
  print(f"NCC_rf:{ncc_rf}")
  print(f"result:{result}")

  save_dir = '/content/drive/MyDrive/CLORD_results'
  os.makedirs(save_dir, exist_ok=True)
  save_path = os.path.join(save_dir, f'NCC_{filename}.png')

  if(ncc_bg > 0.9 and ncc_rf > 0.9):
    break

  count = count + 1

def Make_T_with_TPS(frames, img, Tb_list, mid=0, max_ransac_iter=5):

  import numpy.linalg as LA
  from scipy.spatial.distance import cdist
  from scipy.linalg import solve

  def tps_kernel(r):
    r[r == 0] = 1e-20
    return r**2 * np.log(r)

  def compute_tps_weights(src_pts, dst_pts, reg=1e-3):
    n = src_pts.shape[0]
    K = tps_kernel(cdist(src_pts, src_pts))
    P = np.hstack((np.ones((n, 1)), src_pts))
    L = np.vstack([
        np.hstack([K + reg * np.eye(n), P]),
        np.hstack([P.T, np.zeros((3, 3))])
    ])
    V = np.vstack([dst_pts, np.zeros((3, 2))])
    W = solve(L, V)
    return W[:n], W[n:]

  def compute_tps_transform(src_pts, dst_pts):
    return compute_tps_weights(src_pts, dst_pts)

  H_list = []
  TPS_list = []

  sift = cv2.SIFT_create()
  bf = cv2.BFMatcher()

  kp0, des0 = sift.detectAndCompute(img, None)

  for i in range(len(frames)):
    kp, des = sift.detectAndCompute(frames[i], None)
    matches = bf.knnMatch(des0, des, k=2)

    good_matches = []
    for m, n in matches:
        if m.distance < 0.75 * n.distance:
            good_matches.append(m)

    pts0 = np.float32([kp0[m.queryIdx].pt for m in good_matches])
    pts1 = np.float32([kp[m.trainIdx].pt for m in good_matches])

    # --- マルチホモグラフィRANSAC ---
    used = np.zeros(len(pts0), dtype=bool)
    clusters_src = []
    clusters_dst = []

    for _ in range(max_ransac_iter):
        if np.sum(~used) < 4:
            break
        sel_src = pts1[~used]
        sel_dst = pts0[~used]
        H, mask = cv2.findHomography(sel_src, sel_dst, cv2.RANSAC, 4.0)
        if H is None or np.sum(mask) < 4:
            break
        inliers = np.where(~used)[0][mask.ravel() == 1]
        used[inliers] = True
        clusters_src.append(pts1[inliers])
        clusters_dst.append(pts0[inliers])

    # --- TPS変換を計算 ---
    all_src = np.vstack(clusters_src)
    all_dst = np.vstack(clusters_dst)
    if len(all_src) >= 6:
        w_tps, a_tps = compute_tps_transform(all_src, all_dst)
        TPS_list.append((w_tps, a_tps, all_src))  # TPS変換関数の格納
        H_list.append(None)  # TPSを使うのでHomographyは不要
    else:
        # fallback: homography
        H, _ = cv2.findHomography(pts1, pts0, cv2.RANSAC, 4.0)
        H_list.append(H)
        TPS_list.append(None)

  return H_list, TPS_list

import cv2
print("OpenCV version:", cv2.__version__)
surf = cv2.xfeatures2d.SURF_create()
print("SURF ready!")

import numpy as np
#import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt

color_num = 3
filename = '/content/fence1_input.avi'

v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

for j in range(frame_num):
  cv2_imshow(frames[j])



print(frames.shape)

(frame_num+1)/2

img = frames[int((frame_num+1)/2)]

surf = cv2.xfeatures2d.SURF_create()

kp0, des0 = surf.detectAndCompute(img, None)

img_surf = cv2.drawKeypoints(img, kp0, None, flags=4)
cv2_imshow(img_surf)
#cv2.imwrite("sift_img.jpg",img_sift)

def contrast(F,con = 128):
  f = mat_to_img(F)

  for i in range(frame_num):

    # コントラスト
    contrast = con

    # コントラスト調整ファクター
    factor = (259 *(contrast + 255)) / (255 *(259 - contrast))

    # float型に変換
    newImage = np.array(f[i], dtype = 'float64')

    # コントラスト調整。（0以下 or 255以上）はクリッピング
    newImage = np.clip((newImage[:,:,:] - 128) * factor + 128, 0, 255)

    # int型に戻す
    newImage = np.array(newImage, dtype = 'uint8')

    f[i] = newImage

  return img_to_mat(f)

#print(F.shape)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue

color_num = 3
filename = '/content/gallery_input.avi'




v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)


mid = int((frame_num)/2)


def optimize(F,thr = 10,max_iter = 300):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.05
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)

  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      #C[:,:,i] = shrinkage_operator()
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      #T = F - E N + Invmu * Y1 + A -Invmu * Y2 + transpose(D) @ (C - Invmu * Y3)
      B[:,:,i] = (1/2)*T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      #Y3[:,:,i] = Y3[:,:,i] + mu * (D * B - C)

    #check_img(B)
    error = LA.norm(B - A) + LA.norm(F - B - E - N)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  F_dash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      F_dash[i,:,j] = frames[i,:,:,j].flatten()

  return F_dash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def Make_T(frames,img,Tb_list):
  rans = 4.0
  #rans = max(frame_height, frame_width) * 0.005  # 例: 1%の誤差許容


  sift = cv2.SIFT_create()
  surf = cv2.xfeatures2d.SURF_create()

  #imgの特徴量抽出
  kp0_sift, des0_sift = sift.detectAndCompute(img, None)
  kp0_surf, des0_surf = surf.detectAndCompute(img, None)


  kp_sift_list = []
  des_sift_list = []

  kp_surf_list = []
  des_surf_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):


    #各framesの特徴量抽出
    kp_sift, des_sift = sift.detectAndCompute(frames[i], None)
    kp_surf, des_surf = surf.detectAndCompute(frames[i], None)

    #kp = np.concatenate((kp,kp_surf))
    #des = np.concatenate((des,des_surf))

    kp_sift_list.append(kp_sift)
    des_sift_list.append(des_sift)
    kp_surf_list.append(kp_surf)
    des_surf_list.append(des_surf)


    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      dis = max(frame_height,frame_width)/75.0
      #dis = 5.0
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      #mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      #mat_surf = bf_surf.match(des0_surf, des_surf_list[i])


      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test
      mat_sift = []
      mat_surf = []
      for m, n in matknn_sift:
        if m.distance < 0.75 * n.distance:
            mat_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.75 * n.distance:
            mat_surf.append(m)

      good_match_sift = []
      good_match_surf = []

      #特徴点の座標抽出
      pts = []
      pts0 = []

      for m in mat_sift:
        x = kp_sift[m.trainIdx].pt
        y = kp0_sift[m.queryIdx].pt

        #pts.append(kp_sift[m.trainIdx].pt)
        #pts0.append(kp0_sift[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_sift.append(m)

      for m in mat_surf:
        x = kp_surf[m.trainIdx].pt
        y = kp0_surf[m.queryIdx].pt

        #pts.append(kp_surf[m.trainIdx].pt)
        #pts0.append(kp0_surf[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_surf.append(m)

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        print("match_fault")
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      if(i ==  mid):
        print("mid_match")
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

    elif mode == 0:
      mat = []
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      '''
      mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      mat_surf = bf_surf.match(des0_surf, des_surf_list[i])
      '''

      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test

      good_match_sift = []
      good_match_surf = []

      for m, n in matknn_sift:
        if m.distance < 1.00 * n.distance:
            good_match_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 1.00 * n.distance:
            good_match_surf.append(m)

      pts = []
      pts0 = []

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        print("match_fault")
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

      if(i ==  mid):
        print("mid_match")
        H = np.eye(3)


    #ソート
    matches_list[i][0] = sorted(matches_list[i][0], key=lambda x: x.distance)
    matches_list[i][1] = sorted(matches_list[i][1], key=lambda x: x.distance)

    #kp,desのリスト化
    kp_list = [kp_sift_list,kp_surf_list]
    des_list = [des_sift_list,des_surf_list]

    #特徴点の座標抽出
    ref_pts_sift = np.float32([kp_sift_list[i][m.trainIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)
    o_pts_sift = np.float32([kp0_sift[m.queryIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)

    sift_matches = cv2.drawMatches(img, kp0_sift, frames[i], kp_sift_list[i], matches_list[i][0], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SIFT Matching{i}")
    plt.show()

    #特徴点の座標抽出
    ref_pts_surf = np.float32([kp_surf_list[i][m.trainIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)
    o_pts_surf = np.float32([kp0_surf[m.queryIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)

    surf_matches = cv2.drawMatches(img, kp0_surf, frames[i], kp_surf_list[i], matches_list[i][1], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(surf_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SURF Matching{i}")
    plt.show()


    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)


  return H_list, H_Inv_List


def TP(F_dash,H_list):
  frames = mat_to_img(F_dash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

def Get_T(R_dash,Tb_list):
  R_dash_frames = mat_to_img(R_dash)
  T, T_Inv = Make_T(R_dash_frames,R_dash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

#main

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 1000 * lamda
lam3 = 10 * lamda
thr = 10


max_iter = 30
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize


B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)

print("make_Tb (Fdash)")
Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Rdash2 = np.clip(2.5*Rdash.astype(np.float32), 0, 255).astype(np.uint8)
#print("make_Tr (Rdash2)")
Tr,Tr_Inv = Get_T(Rdash2,Tb)
Fr = TP(Rdash2,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)



#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))

  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,thr)
  print("check_B")
  check_img(B)

  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  Tr, Tr_Inv = Get_T(np.clip(2.5*Rdash.astype(np.float64), 0, 255).astype(np.uint8),Tb)
  #Tr, Tr_Inv = Get_T(Rdash,Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,thr)
  print("check_R")
  check_img(R)

  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(Bdash,Tr)

  count = count + 1

#check_img(contrast(Rdash,5))
check_img(np.clip(2.5*Rdash.astype(np.float64), 0, 255).astype(np.uint8))

#print(F.shape)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue

color_num = 3
filename = '/content/gallery_input.avi'
MAX_PIXEL = 255
MIN_PIXEL = 0



v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

mid = int((frame_num)/2)

def optimize(F,Wb,thr = 10,max_iter = 300):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  def C_opt(Cin,Wb,Invmu):
    C = np.zeros_like(Cin)

    return shrinkage_operator(Cin, Wb * lam3 * Invmu)
    '''
    for i in range(frame_num):
      for j in range(Cin.shape[1]):
        C[i,j] = shrinkage_operator(Cin[i,j],Wb[i,j]*lam3*Invmu)

    return C
    '''


  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.001
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)



  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"opt_count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      C[:,:,i] = C_opt(Make_edge_2d(B[:,:,i]) + Invmu * Y3[:,:,i],Wb[:,:,i],Invmu)
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      #T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i] + Make_DC(C[:,:,i] - Invmu * Y3[:,:,i])
      B[:,:,i] = (1/6)*T
      #B[:,:,i] = Inv(transpose(D[:,:,i]) @ D[:,:,i] + 2*I ) * T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      Y3[:,:,i] = Y3[:,:,i] + mu * (Make_edge_2d(B[:,:,i]) - C[:,:,i])

    B = np.clip(B, MIN_PIXEL,MAX_PIXEL)
    error = LA.norm(B - A) + LA.norm(F - B - E - N) + LA.norm(Make_edge_D1(B) - C)
    #error = LA.norm(B - A) + LA.norm(F - B - E - N) + LA.norm(D @ B - C)
    check_img(B)

    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  F_dash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      F_dash[i,:,j] = frames[i,:,:,j].flatten()

  return F_dash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames


def Make_T(frames,img,Tb_list):
  rans = 3.5
  sift = cv2.SIFT_create()
  surf = cv2.xfeatures2d.SURF_create()

  #imgの特徴量抽出
  kp0_sift, des0_sift = sift.detectAndCompute(img, None)
  kp0_surf, des0_surf = surf.detectAndCompute(img, None)


  kp_sift_list = []
  des_sift_list = []

  kp_surf_list = []
  des_surf_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):


    #各framesの特徴量抽出
    kp_sift, des_sift = sift.detectAndCompute(frames[i], None)
    kp_surf, des_surf = surf.detectAndCompute(frames[i], None)

    #kp = np.concatenate((kp,kp_surf))
    #des = np.concatenate((des,des_surf))

    kp_sift_list.append(kp_sift)
    des_sift_list.append(des_sift)
    kp_surf_list.append(kp_surf)
    des_surf_list.append(des_surf)


    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      #dis = max(frame_height,frame_width)/100.0
      dis = 10.0
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      #mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      #mat_surf = bf_surf.match(des0_surf, des_surf_list[i])


      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test
      mat_sift = []
      mat_surf = []
      for m, n in matknn_sift:
        if m.distance < 0.75 * n.distance:
            mat_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.75 * n.distance:
            mat_surf.append(m)

      good_match_sift = []
      good_match_surf = []

      #特徴点の座標抽出
      pts = []
      pts0 = []

      for m in mat_sift:
        x = kp_sift[m.trainIdx].pt
        y = kp0_sift[m.queryIdx].pt

        #pts.append(kp_sift[m.trainIdx].pt)
        #pts0.append(kp0_sift[m.queryIdx].pt)


        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(x - y) > dis:
          good_match_sift.append(m)

      for m in mat_surf:
        x = kp_surf[m.trainIdx].pt
        y = kp0_surf[m.queryIdx].pt

        #pts.append(kp_surf[m.trainIdx].pt)
        #pts0.append(kp0_surf[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(x - y) > dis:
          good_match_surf.append(m)

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

    elif mode == 0:
      mat = []
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      '''
      mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      mat_surf = bf_surf.match(des0_surf, des_surf_list[i])
      '''

      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test

      good_match_sift = []
      good_match_surf = []

      for m, n in matknn_sift:
        if m.distance < 0.65 * n.distance:
            good_match_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.65 * n.distance:
            good_match_surf.append(m)

      pts = []
      pts0 = []

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])


    #ソート
    matches_list[i][0] = sorted(matches_list[i][0], key=lambda x: x.distance)
    matches_list[i][1] = sorted(matches_list[i][1], key=lambda x: x.distance)

    #kp,desのリスト化
    kp_list = [kp_sift_list,kp_surf_list]
    des_list = [des_sift_list,des_surf_list]

    #特徴点の座標抽出
    ref_pts_sift = np.float32([kp_sift_list[i][m.trainIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)
    o_pts_sift = np.float32([kp0_sift[m.queryIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)

    sift_matches = cv2.drawMatches(img, kp0_sift, frames[i], kp_sift_list[i], matches_list[i][0], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SIFT Matching{i}")
    plt.show()

    #特徴点の座標抽出
    ref_pts_surf = np.float32([kp_surf_list[i][m.trainIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)
    o_pts_surf = np.float32([kp0_surf[m.queryIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)

    surf_matches = cv2.drawMatches(img, kp0_surf, frames[i], kp_surf_list[i], matches_list[i][1], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(surf_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SURF Matching{i}")
    plt.show()


    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)


  return H_list, H_Inv_List


def TP(F_dash,H_list):
  frames = mat_to_img(F_dash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

def Get_T(R_dash,Tb_list):
  R_dash_frames = mat_to_img(R_dash)
  T, T_Inv = Make_T(R_dash_frames,R_dash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

#3次元行列の積からエッジ画像生成
def Make_edge_3D(D,B):
  DB = np.zeros_like(B).astype(int)

  for i in range(color_num):
    DB[:,:,i] = B[:,:,i] @ D[:,:,i].T
  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

#3次元微分フィルタ
def Make_edge_D1(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+1)%size,k])
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+int(frame_width))%size,k])
        DB[i,j,k] = 2 * int(B[i,j%size,k]) - int(B[i,(j+1)%size,k]) - int(B[i,(j+int(frame_width))%size,k])

  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

#2次元微分フィルタ
def Make_edge_2d(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      DB[i,j] = 2 * int(B[i,j%size]) - int(B[i,(j+1)%size]) - int(B[i,(j+int(frame_width))%size])

  DB = np.clip(np.abs(DB),MIN_PIXEL,MAX_PIXEL).astype(np.uint8)
  return DB

#3次元ソーベルフィルタ
def Make_edge_D2(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  w = int(frame_width)

  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        DB[i,j,k] = int(B[i,(j+1)%size,k]) - int(B[i,(j-1)%size,k]) + int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) - int(B[i,(j-1+w)%size,k])
        DB[i,j,k] += int(B[i,(j+w)%size,k]) - int(B[i,(j-w)%size,k]) - int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) + int(B[i,(j-1+w)%size,k])

  DB = np.clip(np.abs(DB),MIN_PIXEL,MAX_PIXEL).astype(np.uint8)
  return DB

#(D^T)*(C-Invmu*Y3)Dは微分フィルタ
def Make_DC(C):
  DC = np.zeros_like(C.T).astype(int)
  temp = np.zeros_like(C.T).astype(int)
  temp = C.T
  size = C.shape[1]
  w = int(frame_width)

  for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
      DC[i,j] = 2 * int(temp[i%size,j]) - int(temp[(i-1)%size,j]) - int(temp[(i-w)%size,j])

  DC = np.clip(np.abs(DC),MIN_PIXEL,MAX_PIXEL).astype(np.uint8)
  return DC.T




def Wb_update(GF,GR):
  Gb = np.zeros_like(GF).astype(float)
  Hr = np.zeros_like(Gb).astype(float)
  Hb = np.zeros_like(Gb).astype(float)
  Hf = np.zeros_like(Gb).astype(float)
  Wb = np.ones_like(Gb).astype(float)
  m = 3
  # ratio = a
  thr = 0.05 * 255
  a = 1.2
  Gf = GF.astype(float)
  Gr = GR.astype(float)
  Gb = gray_mat(np.clip(Gf.astype(int) - Gr.astype(int),MIN_PIXEL,MAX_PIXEL))
  Hf = gray_mat(np.where(Gf >thr, MAX_PIXEL, MIN_PIXEL))
  Hb = gray_mat(np.where(Gb > thr, MAX_PIXEL, MIN_PIXEL))
  Hr = gray_mat(np.where(Gr > thr, MAX_PIXEL, MIN_PIXEL))



  for i in range(int(frame_height) * int(frame_width)):

    for j in range(frame_num):
      for k in range(color_num):
        if(Hf[j,i,k] == MAX_PIXEL and abs(Gb[j,i,k]) > a * abs(Gr[j,i,k])):
          Wb[j,i,k] = 0

        elif(Hf[j,i,k] == MAX_PIXEL and abs(Gr[j,i,k]) > a * abs(Gb[j,i,k])):
          Wb[j,i,k] = 5

        elif(Hf[j,i,k] == MIN_PIXEL and (abs(Gb[j,i,k]) > thr or abs(Gr[j,i,k]) > thr)):
          Wb[j,i,k] = 5

        else:
          Wb[j,i,k] = 1

    for k in range(color_num):
      if(sum(Wb[:,i,k]) < m):
        Wb[:,i,k] = 0


  Wb = gray_mat(np.clip(Wb,0,255).astype(np.uint8))
  return Wb

def MakeD(size):
  D = np.zeros((size, size, 3), dtype=np.int8)

  for i in range(size):
    for k in range(color_num):
      D[(i)%size, (i-1)%size,k] = 1
      D[(i)%size, i%size,k] = -1

  return D

def gray_mat(F):
  frames = mat_to_img(F)
  gray_frames = np.zeros_like(frames)
  for i in range(frame_num):
    for j in range(color_num):
      gray_frames[i,:,:,j] = cv2.cvtColor(frames[i], cv2.COLOR_BGR2GRAY)


  gray_F = img_to_mat(gray_frames)
  return gray_F

#main

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 2000 * lamda
lam3 = 10 * lamda
thr = 10

mid = int((frame_num)/2)
max_iter = 1
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize
D = MakeD(Fdash.shape[1])

B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(Rdash,Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)



#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))



  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #Wb_update
  Wb = Wb_update(gray_mat(Make_edge_D1(TP(Fdash,Tb))),gray_mat(Make_edge_D1(TP(TP(R,Tr_Inv),Tb))))

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,Wb,thr)
  print("check_B")
  check_img(B)

  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  Tr, Tr_Inv = Get_T(Rdash,Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #Wr_update
  Wr = Wb_update(gray_mat(Make_edge_D1(TP(Fdash,Tr))),gray_mat(Make_edge_D1(TP(TP(B,Tb_Inv),Tr))))

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,Wr,thr)
  print("check_R")
  check_img(R)

  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(Bdash,Tr)

  count = count + 1

dis = max(frame_height,frame_width)/100.0
print(dis)

#check_img(gray_mat(Make_edge_D1(TP(Fdash,Tb))))
check_img(np.where((Make_edge_D1(TP(Fdash,Tb))) >255*0.05, MAX_PIXEL, MIN_PIXEL))

check_img(Wb*51)

def gray_mat(F):
  frames = mat_to_img(F)
  gray_frames = np.zeros_like(frames)
  for i in range(frame_num):
    for j in range(color_num):
      gray_frames[i,:,:,j] = cv2.cvtColor(frames[i], cv2.COLOR_BGR2GRAY)


  gray_F = img_to_mat(gray_frames)
  return gray_F

def NCC(truth,est):
  NCC  = None

  for j in range(color_num):
    img1 = truth[i,:,:,j].flatten()
    img2 = est[i,:,:,j].flatten()

    img1 -= np.mean(img1)
    img2 -= np.mean(img2)

    ncc_ave.append(np.sum(img1 * img2) / (LA.norm(img1) * LA.norm(img2)))

  NCC = (sum(ncc_ave)/3.0)
  return NCC

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue


frame_num = 5

im = []

for i in range(frame_num):
  img_file = str(f'/content/hanoi_input_{i+1}.png')
  temp = cv2.imread(img_file)
  im.append(temp)
  cv2_imshow(im[i])
  print(im[i].shape)
  print(im[i].dtype)


frame_height = im[0].shape[0]
frame_width = im[0].shape[1]

#print(F.shape)

color_num = 3
MAX_PIXEL = 255
MIN_PIXEL = 0

truth_bg = []

for i in range(frame_num):
  img_file = str(f'/content/hanoi_bg_{i+1}.png')
  temp = cv2.imread(img_file)
  truth_bg.append(temp)
  #cv2_imshow(truth_bg[i])
  print(truth_bg[i].shape)
  print(truth_bg[i].dtype)

truth_rf = []

for i in range(frame_num):
  img_file = str(f'/content/hanoi_rf_{i+1}.png')
  temp = cv2.imread(img_file)
  truth_rf.append(temp)
  #cv2_imshow(truth_rf[i])
  print(truth_rf[i].shape)
  print(truth_rf[i].dtype)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  frames[i] = im[i]

  # True

  print(type(frames))
  # <class 'numpy.ndarray'>

  print(frames.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

mid = int((frame_num)/2)

def optimize(F,Wb,thr = 10,max_iter = 300,mid=mid):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  def C_opt(Cin,Wb,Invmu):
    return shrinkage_operator(Cin, Wb * lam3 * Invmu)
    '''
    C = np.zeros_like(Cin)
    for i in range(frame_num):
      for j in range(Cin.shape[1]):
        C[i,j] = shrinkage_operator(Cin[i,j],Wb[i,j]*lam3*Invmu)

    return C
    '''


  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.001
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)



  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"opt_count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      C[:,:,i] = C_opt(Make_edge_2d(B[:,:,i]) + Invmu * Y3[:,:,i],Wb[:,:,i],Invmu)
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      #T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i] + Make_DC(C[:,:,i] - Invmu * Y3[:,:,i])
      B[:,:,i] = (1/6)*T
      #B[:,:,i] = Inv(transpose(D[:,:,i]) @ D[:,:,i] + 2*I ) * T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      Y3[:,:,i] = Y3[:,:,i] + mu * (Make_edge_2d(B[:,:,i]) - C[:,:,i])

    B = np.clip(B, MIN_PIXEL,MAX_PIXEL)
    error = LA.norm(B - A) + LA.norm(F - B - E - N) + LA.norm(Make_edge_D1(B) - C)
    #error = LA.norm(B - A) + LA.norm(F - B - E - N) + LA.norm(D @ B - C)
    check_img(B)

    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  F_dash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      F_dash[i,:,j] = frames[i,:,:,j].flatten()

  return F_dash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames


def Make_T(frames,img,Tb_list):
  rans = 5.0
  sift = cv2.SIFT_create()
  surf = cv2.xfeatures2d.SURF_create()

  #imgの特徴量抽出
  kp0_sift, des0_sift = sift.detectAndCompute(img, None)
  kp0_surf, des0_surf = surf.detectAndCompute(img, None)


  kp_sift_list = []
  des_sift_list = []

  kp_surf_list = []
  des_surf_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):


    #各framesの特徴量抽出
    kp_sift, des_sift = sift.detectAndCompute(frames[i], None)
    kp_surf, des_surf = surf.detectAndCompute(frames[i], None)

    #kp = np.concatenate((kp,kp_surf))
    #des = np.concatenate((des,des_surf))

    kp_sift_list.append(kp_sift)
    des_sift_list.append(des_sift)
    kp_surf_list.append(kp_surf)
    des_surf_list.append(des_surf)


    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      #dis = max(frame_height,frame_width)/100.0
      dis = 15.0
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      #mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      #mat_surf = bf_surf.match(des0_surf, des_surf_list[i])


      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test
      mat_sift = []
      mat_surf = []
      for m, n in matknn_sift:
        if m.distance < 0.75 * n.distance:
            mat_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.75 * n.distance:
            mat_surf.append(m)

      good_match_sift = []
      good_match_surf = []

      #特徴点の座標抽出
      pts = []
      pts0 = []

      for m in mat_sift:
        x = kp_sift[m.trainIdx].pt
        y = kp0_sift[m.queryIdx].pt

        #pts.append(kp_sift[m.trainIdx].pt)
        #pts0.append(kp0_sift[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_sift.append(m)

      for m in mat_surf:
        x = kp_surf[m.trainIdx].pt
        y = kp0_surf[m.queryIdx].pt

        #pts.append(kp_surf[m.trainIdx].pt)
        #pts0.append(kp0_surf[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_surf.append(m)

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

    elif mode == 0:
      mat = []
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      '''
      mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      mat_surf = bf_surf.match(des0_surf, des_surf_list[i])
      '''

      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test

      good_match_sift = []
      good_match_surf = []

      for m, n in matknn_sift:
        if m.distance < 0.70 * n.distance:
            good_match_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.70 * n.distance:
            good_match_surf.append(m)

      pts = []
      pts0 = []

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])


    #ソート
    matches_list[i][0] = sorted(matches_list[i][0], key=lambda x: x.distance)
    matches_list[i][1] = sorted(matches_list[i][1], key=lambda x: x.distance)

    #kp,desのリスト化
    kp_list = [kp_sift_list,kp_surf_list]
    des_list = [des_sift_list,des_surf_list]

    #特徴点の座標抽出
    ref_pts_sift = np.float32([kp_sift_list[i][m.trainIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)
    o_pts_sift = np.float32([kp0_sift[m.queryIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)

    sift_matches = cv2.drawMatches(img, kp0_sift, frames[i], kp_sift_list[i], matches_list[i][0], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SIFT Matching{i}")
    plt.show()

    #特徴点の座標抽出
    ref_pts_surf = np.float32([kp_surf_list[i][m.trainIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)
    o_pts_surf = np.float32([kp0_surf[m.queryIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)

    surf_matches = cv2.drawMatches(img, kp0_surf, frames[i], kp_surf_list[i], matches_list[i][1], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(surf_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SURF Matching{i}")
    plt.show()


    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)


  return H_list, H_Inv_List


def TP(F_dash,H_list):
  frames = mat_to_img(F_dash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

def Get_T(R_dash,Tb_list):
  R_dash_frames = mat_to_img(Rdash)
  T, T_Inv = Make_T(R_dash_frames,R_dash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

#3次元行列の積からエッジ画像生成
def Make_edge_3D(D,B):
  DB = np.zeros_like(B).astype(int)

  for i in range(color_num):
    DB[:,:,i] = B[:,:,i] @ D[:,:,i].T
  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

#3次元微分フィルタ
def Make_edge_D1(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+1)%size,k])
        #DB[i,j,k] = int(B[i,j%size,k]) - int(B[i,(j+int(frame_width))%size,k])
        DB[i,j,k] = 2 * int(B[i,j%size,k]) - int(B[i,(j+1)%size,k]) - int(B[i,(j+int(frame_width))%size,k])

  DB = np.clip(np.abs(DB),0,255).astype(np.uint8)
  return DB

#2次元微分フィルタ
def Make_edge_2d(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      DB[i,j] = 2 * int(B[i,j%size]) - int(B[i,(j+1)%size]) - int(B[i,(j+int(frame_width))%size])

  DB = np.clip(np.abs(DB),MIN_PIXEL,MAX_PIXEL).astype(np.uint8)
  return DB

#3次元ソーベルフィルタ
def Make_edge_D2(B):
  DB = np.zeros_like(B).astype(int)
  size = B.shape[1]
  w = int(frame_width)

  for i in range(B.shape[0]):
    for j in range(B.shape[1]):
      for k in range(color_num):
        DB[i,j,k] = int(B[i,(j+1)%size,k]) - int(B[i,(j-1)%size,k]) + int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) - int(B[i,(j-1+w)%size,k])
        DB[i,j,k] += int(B[i,(j+w)%size,k]) - int(B[i,(j-w)%size,k]) - int(B[i,(j+1-w)%size,k]) + int(B[i,(j+1+w)%size,k]) - int(B[i,(j-1-w)%size,k]) + int(B[i,(j-1+w)%size,k])

  DB = np.clip(np.abs(DB),MIN_PIXEL,MAX_PIXEL).astype(np.uint8)
  return DB

#(D^T)*(C-Invmu*Y3)Dは微分フィルタ
def Make_DC(C):
  DC = np.zeros_like(C.T).astype(int)
  temp = np.zeros_like(C.T).astype(int)
  temp = C.T
  size = C.shape[1]
  w = int(frame_width)

  for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
      DC[i,j] = 2 * int(temp[i%size,j]) - int(temp[(i-1)%size,j]) - int(temp[(i-w)%size,j])

  DC = np.clip(np.abs(DC),MIN_PIXEL,MAX_PIXEL).astype(np.uint8)
  return DC.T




def Wb_update(GF,GR):
  Gb = np.zeros_like(GF).astype(float)
  Hr = np.zeros_like(Gb).astype(float)
  Hb = np.zeros_like(Gb).astype(float)
  Hf = np.zeros_like(Gb).astype(float)
  Wb = np.ones_like(Gb).astype(float)
  m = 3
  # ratio = a
  thr = 0.05 * 255
  a = 1.2
  Gf = GF.astype(float)
  Gr = GR.astype(float)
  Gb = gray_mat(np.clip(Gf.astype(int) - Gr.astype(int),MIN_PIXEL,MAX_PIXEL))
  Hf = gray_mat(np.where(Gf >thr, MAX_PIXEL, MIN_PIXEL))
  Hb = gray_mat(np.where(Gb > thr, MAX_PIXEL, MIN_PIXEL))
  Hr = gray_mat(np.where(Gr > thr, MAX_PIXEL, MIN_PIXEL))



  for i in range(int(frame_height) * int(frame_width)):

    for j in range(frame_num):
      for k in range(color_num):
        if(Hf[j,i,k] == MAX_PIXEL and abs(Gb[j,i,k]) > a * abs(Gr[j,i,k])):
          Wb[j,i,k] = 0

        elif(Hf[j,i,k] == MAX_PIXEL and abs(Gr[j,i,k]) > a * abs(Gb[j,i,k])):
          Wb[j,i,k] = 5

        elif(Hf[j,i,k] == MIN_PIXEL and (abs(Gb[j,i,k]) > thr or abs(Gr[j,i,k]) > thr)):
          Wb[j,i,k] = 5

        else:
          Wb[j,i,k] = 1

    for k in range(color_num):
      if(sum(Wb[:,i,k]) < m):
        Wb[:,i,k] = 0


  Wb = gray_mat(np.clip(Wb,0,255).astype(np.uint8))
  return Wb

def MakeD(size):
  D = np.zeros((size, size, 3), dtype=np.int8)

  for i in range(size):
    for k in range(color_num):
      D[(i)%size, (i-1)%size,k] = 1
      D[(i)%size, i%size,k] = -1

  return D

def gray_mat(F):
  frames = mat_to_img(F)
  gray_frames = np.zeros_like(frames)
  for i in range(frame_num):
    for j in range(color_num):
      gray_frames[i,:,:,j] = cv2.cvtColor(frames[i], cv2.COLOR_BGR2GRAY)


  gray_F = img_to_mat(gray_frames)
  return gray_F

def NCC(truth, est):
    ncc_ave = []
    for i in range(frame_num):
        for j in range(color_num):
            img1 = truth[i][:,:,j].flatten().astype(np.float32)
            img2 = est[i][:,:,j].flatten().astype(np.float32)

            img1 -= np.mean(img1)
            img2 -= np.mean(img2)

            denom = LA.norm(img1) * LA.norm(img2)
            if denom != 0:
                ncc_ave.append(np.sum(img1 * img2) / denom)
            else:
                ncc_ave.append(0.0)

    return np.mean(ncc_ave)

#main

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 2000 * lamda
lam3 = 10 * lamda
thr = 10


max_iter = 1
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize
D = MakeD(Fdash.shape[1])

B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(Rdash,Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)



#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))



  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #Wb_update
  Wb = Wb_update(gray_mat(Make_edge_D1(TP(Fdash,Tb))),gray_mat(Make_edge_D1(TP(TP(R,Tr_Inv),Tb))))

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,Wb,thr)
  print("check_B")
  check_img(B)

  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  Tr, Tr_Inv = Get_T(Rdash,Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #Wr_update
  Wr = Wb_update(gray_mat(Make_edge_D1(TP(Fdash,Tr))),gray_mat(Make_edge_D1(TP(TP(B,Tb_Inv),Tr))))

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,Wr,thr)
  print("check_R")
  check_img(R)

  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(Bdash,Tr)

  print(f"NCC_bg:{NCC(truth_bg,mat_to_img(B))}")
  print(f"NCC_rf:{NCC(truth_rf,mat_to_img(R))}")
  if(NCC(truth_bg,mat_to_img(B)) > 0.7 and NCC(truth_rf,mat_to_img(R)) > 0.7):
    break

  count = count + 1

"""Wb未実装Ver"""

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue
from matplotlib import pyplot as plt


frame_num = 5
filename = "toy"
im = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_input_{i+1}.png')
  temp = cv2.imread(img_file)
  im.append(temp)
  cv2_imshow(im[i])
  print(im[i].shape)
  print(im[i].dtype)


frame_height = im[0].shape[0]
frame_width = im[0].shape[1]
mid = int((frame_num)/2)

#print(F.shape)

color_num = 3
MAX_PIXEL = 255
MIN_PIXEL = 0

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 1000 * lamda
lam3 = 10 * lamda
thr = 10

tr_bg = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_bg_{i+1}.png')
  temp = cv2.imread(img_file)
  tr_bg.append(temp)
  #cv2_imshow(truth_bg[i])
  print(tr_bg[i].shape)
  print(tr_bg[i].dtype)


tr_rf = []

for i in range(frame_num):
  img_file = str(f'/content/{filename}_rf_{i+1}.png')
  temp = cv2.imread(img_file)
  tr_rf.append(temp)
  #cv2_imshow(truth_rf[i])
  print(tr_rf[i].shape)
  print(tr_rf[i].dtype)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)
truth_bg = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)
truth_rf = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  frames[i] = im[i]
  truth_bg[i] = tr_bg[i]
  truth_rf[i] = tr_rf[i]

  # True

  print(type(frames))
  # <class 'numpy.ndarray'>

  print(frames.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

mid = int((frame_num)/2)

def optimize(F,thr = 10,max_iter = 300,lam1=lam1, lam2=lam2,lam3=lam3):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.05
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.15
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)

  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]

      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      #C[:,:,i] = shrinkage_operator()
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      #T = F - E N + Invmu * Y1 + A -Invmu * Y2 + transpose(D) @ (C - Invmu * Y3)
      B[:,:,i] = (1/2)*T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      #Y3[:,:,i] = Y3[:,:,i] + mu * (D * B - C)

    error = LA.norm(B - A) + LA.norm(F - B - E - N)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  F_dash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      F_dash[i,:,j] = frames[i,:,:,j].flatten()

  return F_dash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def Make_T(frames,img,Tb_list,mid=mid):
  #rans = 4.0
  rans = max(frame_height, frame_width) * 0.01  # 例: 1%の誤差許容


  sift = cv2.SIFT_create()
  surf = cv2.xfeatures2d.SURF_create()

  #imgの特徴量抽出
  kp0_sift, des0_sift = sift.detectAndCompute(img, None)
  kp0_surf, des0_surf = surf.detectAndCompute(img, None)


  kp_sift_list = []
  des_sift_list = []

  kp_surf_list = []
  des_surf_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):


    #各framesの特徴量抽出
    kp_sift, des_sift = sift.detectAndCompute(frames[i], None)
    kp_surf, des_surf = surf.detectAndCompute(frames[i], None)

    #kp = np.concatenate((kp,kp_surf))
    #des = np.concatenate((des,des_surf))

    kp_sift_list.append(kp_sift)
    des_sift_list.append(des_sift)
    kp_surf_list.append(kp_surf)
    des_surf_list.append(des_surf)


    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      dis = max(frame_height,frame_width)/75.0
      #dis = 5.0
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      #mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      #mat_surf = bf_surf.match(des0_surf, des_surf_list[i])


      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test
      mat_sift = []
      mat_surf = []
      for m, n in matknn_sift:
        if m.distance < 0.75 * n.distance:
            mat_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.75 * n.distance:
            mat_surf.append(m)

      good_match_sift = []
      good_match_surf = []

      #特徴点の座標抽出
      pts = []
      pts0 = []

      for m in mat_sift:
        x = kp_sift[m.trainIdx].pt
        y = kp0_sift[m.queryIdx].pt

        #pts.append(kp_sift[m.trainIdx].pt)
        #pts0.append(kp0_sift[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_sift.append(m)

      for m in mat_surf:
        x = kp_surf[m.trainIdx].pt
        y = kp0_surf[m.queryIdx].pt

        #pts.append(kp_surf[m.trainIdx].pt)
        #pts0.append(kp0_surf[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        trans_x = Tb_list[i] @ x
        trans_x = trans_x/trans_x[2]

        if np.linalg.norm(trans_x - y) > dis:
          good_match_surf.append(m)

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        print("match_fault")
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

    elif mode == 0:
      mat = []
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      '''
      mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      mat_surf = bf_surf.match(des0_surf, des_surf_list[i])
      '''

      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test

      good_match_sift = []
      good_match_surf = []

      for m, n in matknn_sift:
        if m.distance < 0.90 * n.distance:
            good_match_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.90 * n.distance:
            good_match_surf.append(m)

      pts = []
      pts0 = []

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, rans)
      else:
        print("match_fault")
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])


    #ソート
    matches_list[i][0] = sorted(matches_list[i][0], key=lambda x: x.distance)
    matches_list[i][1] = sorted(matches_list[i][1], key=lambda x: x.distance)

    #kp,desのリスト化
    kp_list = [kp_sift_list,kp_surf_list]
    des_list = [des_sift_list,des_surf_list]

    #特徴点の座標抽出
    ref_pts_sift = np.float32([kp_sift_list[i][m.trainIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)
    o_pts_sift = np.float32([kp0_sift[m.queryIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)

    sift_matches = cv2.drawMatches(img, kp0_sift, frames[i], kp_sift_list[i], matches_list[i][0], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SIFT Matching{i}")
    plt.show()

    #特徴点の座標抽出
    ref_pts_surf = np.float32([kp_surf_list[i][m.trainIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)
    o_pts_surf = np.float32([kp0_surf[m.queryIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)

    surf_matches = cv2.drawMatches(img, kp0_surf, frames[i], kp_surf_list[i], matches_list[i][1], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(surf_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SURF Matching{i}")
    plt.show()


    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)


  return H_list, H_Inv_List



def TP(F_dash,H_list):
  frames = mat_to_img(F_dash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  return img_to_mat(warped_img)

def Get_T(R_dash,Tb_list):
  R_dash_frames = mat_to_img(R_dash)
  T, T_Inv = Make_T(R_dash_frames,R_dash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

def NCC(truth, est):
    ncc_ave = []
    for i in range(frame_num):
      #temp= cv2.matchTemplate(est[i], truth[i], cv2.TM_CCOEFF_NORMED)
      #ncc_ave.append(temp)
        for j in range(color_num):
            img1 = truth[i][:,:,j].flatten().astype(np.float32)
            img2 = est[i][:,:,j].flatten().astype(np.float32)

            img1 -= np.mean(img1)
            img2 -= np.mean(img2)

            denom = LA.norm(img1) * LA.norm(img2)
            if denom != 0:
                ncc_ave.append(np.sum(img1 * img2) / denom)
            else:
                ncc_ave.append(0.0)

    return np.mean(ncc_ave)

#main




max_iter = 100
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize


B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(np.clip(2.0*Rdash.astype(np.float32),0,255).astype(np.uint8),Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini



print("check_origin_R")
check_img(R)


result = []

ncc_bg = NCC(truth_bg, mat_to_img(TP(B,Tb_Inv)))
ncc_rf = NCC(truth_rf, mat_to_img(TP(R,Tr_Inv)))


result.append([ncc_bg, ncc_rf])
print(f"NCC_bg:{ncc_bg}")
print(f"NCC_rf:{ncc_rf}")
#CLORD
count = 0
while (count < max_iter):
  print(f"CLORD_count:{count}")
  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))

  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,thr)
  print("check_B")
  check_img(B)

  img_B = mat_to_img(B)
  for i in range(frame_num):
    cv2.imwrite(f'/content/drive/My Drive/output_bg_{filename}_{i+1}.png', img_B[i])



  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tr, Tr_Inv = Get_T(Rdash,Tb)
  Tr, Tr_Inv = Get_T(np.clip(2.0*Rdash.astype(np.float32),0,255).astype(np.uint8),Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,thr)
  print("check_R")
  check_img(R)

  img_R = mat_to_img(R)
  for i in range(frame_num):
    cv2.imwrite(f'/content/drive/My Drive/output_rf_{filename}_{i+1}.png', img_R[i])


  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(np.clip(2.0*Bdash.astype(np.float32),0,255).astype(np.uint8),Tr)


  #result.append([NCC(mat_to_img(TP(img_to_mat(truth_bg),Tb)),mat_to_img(B)),NCC(mat_to_img(TP(img_to_mat(truth_rf),Tr)),mat_to_img(R))])
  #print(f"NCC_bg:{result[count][0]}")
  #print(f"NCC_rf:{result[count][1]}")

  #ncc_bg = NCC(mat_to_img(TP(img_to_mat(truth_bg), Tb)), mat_to_img(B))
  #ncc_rf = NCC(mat_to_img(TP(img_to_mat(truth_rf), Tr)), mat_to_img(R))

  ncc_bg = NCC(truth_bg, mat_to_img(TP(B,Tb_Inv)))
  ncc_rf = NCC(truth_rf, mat_to_img(TP(R,Tr_Inv)))


  result.append([ncc_bg, ncc_rf])
  print(f"NCC_bg:{ncc_bg}")
  print(f"NCC_rf:{ncc_rf}")
  print(f"result:{result}")

  save_dir = '/content/drive/MyDrive/CLORD_results'
  os.makedirs(save_dir, exist_ok=True)
  save_path = os.path.join(save_dir, f'NCC_{filename}.png')

  if(ncc_bg > 0.9 and ncc_rf > 0.9):
    break

  count = count + 1

from matplotlib import pyplot as plt
#print(result[0])
bg = []
rf = []
y = []
for i in range(len(result)):
  bg.append(result[i][0])
  rf.append(result[i][1])
  y.append(int(i+1))

#print(bg)
fig = plt.figure()
ax = fig.add_subplot(111)

plt.plot(y, bg, label='NCC_bg')
print(bg)
plt.plot(y, rf, label='NCC_rf')
print(rf)

print(y)

ax.set_ylabel('NCC')
ax.set_xlabel(f'CLORD_iter(count:{len(result)})')

ax.set_ylim(0,1)
#ax.set_xlim(1,max_iter+1)
#ax.set_xlim(1,len(result))
#plt.xticks(y)

plt.title(f'NCC_{filename}')
plt.legend()
plt.show()

from matplotlib import pyplot as plt
from google.colab import drive
import os

# Drive をマウント
drive.mount('/content/drive')

# 保存先のパスを指定（例：MyDrive/CLORD_results/CLORD_NCC_plot.png）
save_dir = '/content/drive/MyDrive/CLORD_results'
os.makedirs(save_dir, exist_ok=True)
save_path = os.path.join(save_dir, f'NCC_{filename}.png')

# データ準備
bg = []
rf = []
y = []
for i in range(len(result)):
    bg.append(result[i][0])
    rf.append(result[i][1])
    y.append(int(i + 1))

# プロット
fig = plt.figure()
ax = fig.add_subplot(111)

plt.plot(y, bg, label='NCC_bg')
plt.plot(y, rf, label='NCC_rf')

ax.set_ylabel('NCC')
ax.set_xlabel(f'CLORD_iter (count: {len(result)})')
ax.set_ylim(0, 1)
plt.title(f'NCC_{filename}')
plt.legend()

# 保存（重要！.png 拡張子を忘れずに）
plt.savefig(save_path)
print(f"保存先: {save_path}")

# 表示
plt.show()