# -*- coding: utf-8 -*-
"""multiview2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoIvvWEOdtaN2rg3qjkqaotPNMgfKaRj
"""

!apt-get update
!apt-get install -y build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev

!git clone https://github.com/opencv/opencv.git
!git clone https://github.com/opencv/opencv_contrib.git

# Commented out IPython magic to ensure Python compatibility.
import os
os.makedirs("opencv_build", exist_ok=True)
# %cd opencv_build

!cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
    -D ENABLE_PRECOMPILED_HEADERS=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D BUILD_EXAMPLES=OFF \
    ../opencv

!make -j4
!make install
!ldconfig

import cv2
print("OpenCV version:", cv2.__version__)
surf = cv2.xfeatures2d.SURF_create()
print("SURF ready!")

import numpy as np
#import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt

color_num = 3
filename = '/content/gallery_input.avi'

v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)

for j in range(frame_num):
  cv2_imshow(frames[j])



print(frames.shape)

(frame_num+1)/2

img = frames[int((frame_num+1)/2)]

surf = cv2.xfeatures2d.SURF_create()

kp0, des0 = surf.detectAndCompute(img, None)

img_surf = cv2.drawKeypoints(img, kp0, None, flags=4)
cv2_imshow(img_surf)
#cv2.imwrite("sift_img.jpg",img_sift)

#print(F.shape)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue

color_num = 3
filename = '/content/gallery_input.avi'




v_file = cv2.VideoCapture(filename)
print(type(v_file))
print(v_file.isOpened())

frame_width = v_file.get(cv2.CAP_PROP_FRAME_WIDTH)
print(frame_width)

frame_height = v_file.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(frame_height)

fps = v_file.get(cv2.CAP_PROP_FPS)
print(fps)

frame_num = v_file.get(cv2.CAP_PROP_FRAME_COUNT)
print(frame_num)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  v_file.set(cv2.CAP_PROP_POS_FRAMES, i)
  ret, frame = v_file.read()
  frames[i] = frame
  print(ret)
  # True

  print(type(frame))
  # <class 'numpy.ndarray'>

  print(frame.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)




def optimize(F,thr = 10,max_iter = 300):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.05
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)

  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      #C[:,:,i] = shrinkage_operator()
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      #T = F - E N + Invmu * Y1 + A -Invmu * Y2 + transpose(D) @ (C - Invmu * Y3)
      B[:,:,i] = (1/2)*T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      #Y3[:,:,i] = Y3[:,:,i] + mu * (D * B - C)

    error = LA.norm(B - A) + LA.norm(F - B - E - N)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      Fdash[i,:,j] = frames[i,:,:,j].flatten()

  return Fdash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def Make_T(frames,img,Tb_list):
  sift = cv2.SIFT_create()
  surf = cv2.xfeatures2d.SURF_create()

  #imgの特徴量抽出
  kp0_sift, des0_sift = sift.detectAndCompute(img, None)
  kp0_surf, des0_surf = surf.detectAndCompute(img, None)


  kp_sift_list = []
  des_sift_list = []

  kp_surf_list = []
  des_surf_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):


    #各framesの特徴量抽出
    kp_sift, des_sift = sift.detectAndCompute(frames[i], None)
    kp_surf, des_surf = surf.detectAndCompute(frames[i], None)

    #kp = np.concatenate((kp,kp_surf))
    #des = np.concatenate((des,des_surf))

    kp_sift_list.append(kp_sift)
    des_sift_list.append(des_sift)
    kp_surf_list.append(kp_surf)
    des_surf_list.append(des_surf)


    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      dis = max(frame_height,frame_width)/100.0
      #dis = 5.0
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      #mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      #mat_surf = bf_surf.match(des0_surf, des_surf_list[i])


      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test
      mat_sift = []
      mat_surf = []
      for m, n in matknn_sift:
        if m.distance < 0.75 * n.distance:
            mat_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.75 * n.distance:
            mat_surf.append(m)

      good_match_sift = []
      good_match_surf = []

      #特徴点の座標抽出
      pts = []
      pts0 = []

      for m in mat_sift:
        x = kp_sift[m.trainIdx].pt
        y = kp0_sift[m.queryIdx].pt

        #pts.append(kp_sift[m.trainIdx].pt)
        #pts0.append(kp0_sift[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        x = Tb_list[i] @ x
        y = Tb_list[i] @ y
        x = x/x[2]
        y = y/y[2]

        if np.linalg.norm(x - y) > dis:
          good_match_sift.append(m)

      for m in mat_surf:
        x = kp_surf[m.trainIdx].pt
        y = kp0_surf[m.queryIdx].pt

        #pts.append(kp_surf[m.trainIdx].pt)
        #pts0.append(kp0_surf[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        x = Tb_list[i] @ x
        y = Tb_list[i] @ y
        x = x/x[2]
        y = y/y[2]

        if np.linalg.norm(x - y) > dis:
          good_match_surf.append(m)

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, 5.0)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

    elif mode == 0:
      mat = []
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      '''
      mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      mat_surf = bf_surf.match(des0_surf, des_surf_list[i])
      '''

      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test

      good_match_sift = []
      good_match_surf = []

      for m, n in matknn_sift:
        if m.distance < 0.65 * n.distance:
            good_match_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.65 * n.distance:
            good_match_surf.append(m)

      pts = []
      pts0 = []

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, 5.0)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])


    #ソート
    matches_list[i][0] = sorted(matches_list[i][0], key=lambda x: x.distance)
    matches_list[i][1] = sorted(matches_list[i][1], key=lambda x: x.distance)

    #kp,desのリスト化
    kp_list = [kp_sift_list,kp_surf_list]
    des_list = [des_sift_list,des_surf_list]

    #特徴点の座標抽出
    ref_pts_sift = np.float32([kp_sift_list[i][m.trainIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)
    o_pts_sift = np.float32([kp0_sift[m.queryIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)

    sift_matches = cv2.drawMatches(img, kp0_sift, frames[i], kp_sift_list[i], matches_list[i][0], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SIFT Matching{i}")
    plt.show()

    #特徴点の座標抽出
    ref_pts_surf = np.float32([kp_surf_list[i][m.trainIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)
    o_pts_surf = np.float32([kp0_surf[m.queryIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)

    surf_matches = cv2.drawMatches(img, kp0_surf, frames[i], kp_surf_list[i], matches_list[i][1], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(surf_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SURF Matching{i}")
    plt.show()


    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)


  return H_list, H_Inv_List

def TP(Fdash,H_list):
  frames = mat_to_img(Fdash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

def Get_T(R_dash,Tb_list):
  Rdash_frames = mat_to_img(Rdash)
  T, T_Inv = Make_T(Rdash_frames,Rdash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

#main

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 1000 * lamda
lam3 = 10 * lamda
thr = 10

mid = int((frame_num)/2)
max_iter = 5
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize


B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(Rdash,Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)



#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))

  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,thr)
  print("check_B")
  check_img(B)

  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  Tr, Tr_Inv = Get_T(Rdash,Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,thr)
  print("check_R")
  check_img(R)

  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(Bdash,Tr)

  count = count + 1

dis = max(frame_height,frame_width)/100.0
print(dis)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue


frame_num = 5

im = []

for i in range(frame_num):
  img_file = str(f'/content/toy_input_{i+1}.png')
  temp = cv2.imread(img_file)
  im.append(temp)
  cv2_imshow(im[i])
  print(im[i].shape)
  print(im[i].dtype)


frame_height = im[0].shape[0]
frame_width = im[0].shape[1]

#print(F.shape)

color_num = 3
MAX_PIXEL = 255
MIN_PIXEL = 0

truth_bg = []

for i in range(frame_num):
  img_file = str(f'/content/toy_bg_{i+1}.png')
  temp = cv2.imread(img_file)
  truth_bg.append(temp)
  #cv2_imshow(truth_bg[i])
  print(truth_bg[i].shape)
  print(truth_bg[i].dtype)

truth_rf = []

for i in range(frame_num):
  img_file = str(f'/content/toy_rf_{i+1}.png')
  temp = cv2.imread(img_file)
  truth_rf.append(temp)
  #cv2_imshow(truth_rf[i])
  print(truth_rf[i].shape)
  print(truth_rf[i].dtype)

frame_num = int(frame_num)
#F = np.zeros_like(frame_width,frame_height,frame_num)
frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

for i in range(frame_num):
  print(i)
  frames[i] = im[i]

  # True

  print(type(frames))
  # <class 'numpy.ndarray'>

  print(frames.shape)
  # (648, 1152, 3)

 # cv2_imshow(frame)


def optimize(F,thr = 10,max_iter = 300):

  def shrinkage_operator(x, tau):
    return np.sign(x) * np.maximum((np.abs(x) - tau), np.zeros_like(x))

  F = np.clip(F, 0,255).astype(np.float32)
  Y1 = np.zeros_like(F)
  Y2 = np.zeros_like(F)
  Y3 = np.zeros_like(F)
  mu = 0.05
  #mu = F.shape[1] * F.shape[2] / (4 * LA.norm(F.reshape(-1, 3), ord=1))
  p = 1.2
  Invmu = 1/mu

  B = np.zeros_like(F)
  A = np.zeros_like(F)
  E = np.zeros_like(F)
  C = np.zeros_like(F)
  N = np.zeros_like(F)

  tol = 1e-7 * LA.norm(F)
  error = np.inf
  count = 0

  #while (LA.norm(B - A) + LA.norm(F - B - E - N))>thr and count < max_iter:
  while count < max_iter:
    print(f"count:{count}")

    U1, S1, Vh1 = LA.svd(B[:,:,0] + Y2[:,:,0] * Invmu, full_matrices=False)
    U2, S2, Vh2 = LA.svd(B[:,:,1] + Y2[:,:,1] * Invmu, full_matrices=False)
    U3, S3, Vh3 = LA.svd(B[:,:,2] + Y2[:,:,2] * Invmu, full_matrices=False)

    U = np.zeros((U1.shape[0], U1.shape[1], 3))
    S = np.zeros((S1.shape[0], 3))
    Vh = np.zeros((Vh1.shape[0], Vh1.shape[1], 3))
    S_lowrank = np.zeros_like(S)

    U[:,:,0] = U1
    U[:,:,1] = U2
    U[:,:,2] = U3

    S[:,0] = S1
    S[:,1] = S2
    S[:,2] = S3

    Vh[:,:,0] = Vh1
    Vh[:,:,1] = Vh2
    Vh[:,:,2] = Vh3

    S_lowrank[0,0] = S[0,0]
    S_lowrank[0,1] = S[0,1]
    S_lowrank[0,2] = S[0,2]

    U = U.astype(np.float32)
    S = S.astype(np.float32)
    Vh = Vh.astype(np.float32)
    S_lowrank = S_lowrank.astype(np.float32)

    for i in range(color_num):

      A[:,:,i] = U[:,:,i] @ np.diag(S_lowrank[:,i]) @ Vh[:,:,i]
      E[:,:,i] = shrinkage_operator(F[:,:,i] - B[:,:,i] - N[:,:,i] + Y1[:,:,i] * Invmu ,lam1 * Invmu)
      #C[:,:,i] = shrinkage_operator()
      N[:,:,i] = (mu / (lam2 + mu)) * (F[:,:,i] - B[:,:,i] - E[:,:,i] + Y1[:,:,i] * Invmu)

      #Inv(transpose(D)*D + 2I) * T
      T = F[:,:,i] - E[:,:,i] - N[:,:,i] + Invmu * Y1[:,:,i] + A[:,:,i] -Invmu * Y2[:,:,i]
      #T = F - E N + Invmu * Y1 + A -Invmu * Y2 + transpose(D) @ (C - Invmu * Y3)
      B[:,:,i] = (1/2)*T

      Y1[:,:,i] = Y1[:,:,i] + mu * (F[:,:,i] - B[:,:,i] - E[:,:,i] - N[:,:,i])
      Y2[:,:,i] = Y2[:,:,i] + mu * (B[:,:,i] - A[:,:,i])
      #Y3[:,:,i] = Y3[:,:,i] + mu * (D * B - C)

    error = LA.norm(B - A) + LA.norm(F - B - E - N)
    count = count + 1

    if error <= tol:
        print("converted! error:{}".format(error))
        break
    else:
      print("error:{}".format(error))

    mu = p * mu
    Invmu = 1/mu

  B = np.clip(B, 0,255).astype(np.uint8)
  return B




def img_to_mat(frames):
  Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      Fdash[i,:,j] = frames[i,:,:,j].flatten()

  return Fdash

def mat_to_img(F):
  frames = np.zeros((int(frame_num), int(frame_height), int(frame_width), 3), dtype=np.uint8)

  for i in range(frame_num):
    for j in range(color_num):
      frames[i,:,:,j] = F[i,:,j].reshape(int(frame_height),int(frame_width))

  return frames

def Make_T(frames,img,Tb_list):
  sift = cv2.SIFT_create()
  surf = cv2.xfeatures2d.SURF_create()

  #imgの特徴量抽出
  kp0_sift, des0_sift = sift.detectAndCompute(img, None)
  kp0_surf, des0_surf = surf.detectAndCompute(img, None)


  kp_sift_list = []
  des_sift_list = []

  kp_surf_list = []
  des_surf_list = []

  bf_list = []
  matches_list = []

  H_list = []
  H_Inv_List = []

  for i in range(frame_num):


    #各framesの特徴量抽出
    kp_sift, des_sift = sift.detectAndCompute(frames[i], None)
    kp_surf, des_surf = surf.detectAndCompute(frames[i], None)

    #kp = np.concatenate((kp,kp_surf))
    #des = np.concatenate((des,des_surf))

    kp_sift_list.append(kp_sift)
    des_sift_list.append(des_sift)
    kp_surf_list.append(kp_surf)
    des_surf_list.append(des_surf)


    #マッチングペアの作成
    if Tb_list == None:
      mode = 0
    else:
      mode = 1

    if mode == 1:
      dis = max(frame_height,frame_width)/100.0
      #dis = 5.0
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      #mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      #mat_surf = bf_surf.match(des0_surf, des_surf_list[i])


      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test
      mat_sift = []
      mat_surf = []
      for m, n in matknn_sift:
        if m.distance < 0.75 * n.distance:
            mat_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.75 * n.distance:
            mat_surf.append(m)

      good_match_sift = []
      good_match_surf = []

      #特徴点の座標抽出
      pts = []
      pts0 = []

      for m in mat_sift:
        x = kp_sift[m.trainIdx].pt
        y = kp0_sift[m.queryIdx].pt

        #pts.append(kp_sift[m.trainIdx].pt)
        #pts0.append(kp0_sift[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        x = Tb_list[i] @ x
        y = Tb_list[i] @ y
        x = x/x[2]
        y = y/y[2]

        if np.linalg.norm(x - y) > dis:
          good_match_sift.append(m)

      for m in mat_surf:
        x = kp_surf[m.trainIdx].pt
        y = kp0_surf[m.queryIdx].pt

        #pts.append(kp_surf[m.trainIdx].pt)
        #pts0.append(kp0_surf[m.queryIdx].pt)

        x = np.array([x[0], x[1], 1.0])
        y = np.array([y[0], y[1], 1.0])

        x = Tb_list[i] @ x
        y = Tb_list[i] @ y
        x = x/x[2]
        y = y/y[2]

        if np.linalg.norm(x - y) > dis:
          good_match_surf.append(m)

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, 5.0)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])

    elif mode == 0:
      mat = []
      bf_sift = cv2.BFMatcher()
      bf_surf = cv2.BFMatcher()

      '''
      mat_sift = bf_sift.match(des0_sift, des_sift_list[i])
      mat_surf = bf_surf.match(des0_surf, des_surf_list[i])
      '''

      matknn_sift = bf_sift.knnMatch(des0_sift, des_sift_list[i], k=2)
      matknn_surf = bf_surf.knnMatch(des0_surf, des_surf_list[i], k=2)

      # Lowe's ratio test

      good_match_sift = []
      good_match_surf = []

      for m, n in matknn_sift:
        if m.distance < 0.65 * n.distance:
            good_match_sift.append(m)

      for m, n in matknn_surf:
        if m.distance < 0.65 * n.distance:
            good_match_surf.append(m)

      pts = []
      pts0 = []

      for m in good_match_sift:
        pts.append(kp_sift[m.trainIdx].pt)
        pts0.append(kp0_sift[m.queryIdx].pt)

      for m in good_match_surf:
        pts.append(kp_surf[m.trainIdx].pt)
        pts0.append(kp0_surf[m.queryIdx].pt)

      pts = np.float32(pts).reshape(-1, 1, 2)
      pts0 = np.float32(pts0).reshape(-1, 1, 2)

      # Homography行列を推定（frames[i] → img）
      if len(pts) > 4 and len(pts0) > 4:
        H, mask = cv2.findHomography(pts, pts0, cv2.RANSAC, 5.0)
      else:
        H = np.eye(3)

      if H is None:
        H = np.eye(3)

      matches_list.append([good_match_sift,good_match_surf])


    #ソート
    matches_list[i][0] = sorted(matches_list[i][0], key=lambda x: x.distance)
    matches_list[i][1] = sorted(matches_list[i][1], key=lambda x: x.distance)

    #kp,desのリスト化
    kp_list = [kp_sift_list,kp_surf_list]
    des_list = [des_sift_list,des_surf_list]

    #特徴点の座標抽出
    ref_pts_sift = np.float32([kp_sift_list[i][m.trainIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)
    o_pts_sift = np.float32([kp0_sift[m.queryIdx].pt for m in matches_list[i][0]]).reshape(-1, 1, 2)

    sift_matches = cv2.drawMatches(img, kp0_sift, frames[i], kp_sift_list[i], matches_list[i][0], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(sift_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SIFT Matching{i}")
    plt.show()

    #特徴点の座標抽出
    ref_pts_surf = np.float32([kp_surf_list[i][m.trainIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)
    o_pts_surf = np.float32([kp0_surf[m.queryIdx].pt for m in matches_list[i][1]]).reshape(-1, 1, 2)

    surf_matches = cv2.drawMatches(img, kp0_surf, frames[i], kp_surf_list[i], matches_list[i][1], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    # 表示
    plt.figure(figsize=(12, 6))
    plt.imshow(cv2.cvtColor(surf_matches, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"SURF Matching{i}")
    plt.show()


    H_list.append(H)
    H_Inv = LA.inv(H)
    H_Inv_List.append(H_Inv)


  return H_list, H_Inv_List

def TP(Fdash,H_list):
  frames = mat_to_img(Fdash)
  warped_img = np.zeros_like(frames)

  h, w = frames.shape[1:3]

  for i in range(frame_num):
    warped_img[i] = cv2.warpPerspective(frames[i], H_list[i], (w, h))

  F = img_to_mat(warped_img)
  return F

def Get_T(R_dash,Tb_list):
  Rdash_frames = mat_to_img(Rdash)
  T, T_Inv = Make_T(Rdash_frames,Rdash_frames[int((frame_num)/2)],Tb_list)

  return T,T_Inv

def check_img(F):
  img = mat_to_img(F)
  for i in range(frame_num):
    cv2_imshow(img[i])
    print(i)

#main

lamda = 1/np.sqrt(max(frame_height,frame_width))
#lam1 = 50 * lamda
#lam2 = 2000 * lamda
#lam3 = 10 * lamda

lam1 = 50 * lamda
lam2 = 1000 * lamda
lam3 = 10 * lamda
thr = 10

mid = int((frame_num)/2)
max_iter = 5
thr = 10


Fdash = np.zeros((int(frame_num) , int(frame_height) * int(frame_width), 3), dtype=np.uint8)
#Initialize


B = np.zeros_like(Fdash)
R = np.zeros_like(Fdash)


Fdash = img_to_mat(frames)


Tb, Tb_Inv = Make_T(frames,frames[mid],None)
Fb = TP(Fdash,Tb)

bg_Ini = np.zeros(Fb.shape[1:])

for i in range(Fb.shape[1]):
  for j in range(color_num):
    bg_Ini[i,j] = min(Fb[:,i,j])

for i in range(frame_num):
  B[i,:,:] = bg_Ini

print("check_origin_B")
check_img(B)
Bdash = TP(B,Tb_Inv)




#Rdash
Rdash = np.clip(Fdash.astype(np.int32) - Bdash.astype(np.int32), 0,255).astype(np.uint8)
check_img(Rdash)
#Tr,Tr_Inv = Get_T(Rdash,Tb)
Tr,Tr_Inv = Get_T(Rdash,Tb)
Fr = TP(Rdash,Tr)


rf_Ini = np.zeros(Fr.shape[1:])

for i in range(Fr.shape[1]):
  for j in range(color_num):
    rf_Ini[i,j] = max(Fr[:,i,j])

for i in range(frame_num):
  R[i,:,:] = rf_Ini

print("check_origin_R")
check_img(R)



#CLORD
count = 0
while (count < max_iter):

  #optimizeB
  #check_img(TP(R,Tr_Inv))
  #check_img(TP(TP(R,Tr_Inv),Tb))

  Fb = np.clip(TP(Fdash,Tb).astype(np.int32) - TP(TP(R,Tr_Inv),Tb).astype(np.int32), 0, 255).astype(np.uint8)
  #check_img(F)

  #check_img(TP(Fdash,Tb))
  print("check_Fb")
  check_img(Fb)
  B = np.zeros_like(Fb)
  B = optimize(Fb,thr)
  print("check_B")
  check_img(B)

  #get new tr
  Rdash = np.clip(Fdash.astype(np.int32) - TP(B,Tb_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  Tr, Tr_Inv = Get_T(Rdash,Tb)
  #Tr, Tr_Inv = Get_T(Rdash,None)

  #optimizeR
  Fr = np.clip(TP(Fdash,Tr).astype(np.int32) - TP(TP(B,Tb_Inv),Tr).astype(np.int32), 0, 255).astype(np.uint8)
  print("check_Fr")
  check_img(Fr)

  R = np.zeros_like(Fr)
  R = optimize(Fr,thr)
  print("check_R")
  check_img(R)

  #get new tb
  Bdash = np.clip(Fdash.astype(np.int32) - TP(R,Tr_Inv).astype(np.int32), 0, 255).astype(np.uint8)
  #Tb, Tb_Inv = Get_T(Bdash,Tr)
  Tb, Tb_Inv = Get_T(Bdash,Tr)

  print(f"NCC_bg:{NCC(truth_bg,mat_to_img(B))}")
  print(f"NCC_rf:{NCC(truth_rf,mat_to_img(R))}")
  if(NCC(truth_bg,mat_to_img(B)) > 0.7 and NCC(truth_rf,mat_to_img(R)) > 0.7):
    break

  count = count + 1

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import numpy.linalg as LA
import matplotlib.pyplot as plt
from ast import FormattedValue


frame_num = 5

im = []

for i in range(frame_num):
  img_file = str(f'/content/toy_input_{i+1}.png')
  temp = cv2.imread(img_file)
  im.append(temp)
  cv2_imshow(im[i])
  print(im[i].shape)
  print(im[i].dtype)